import { defineConfig, type Options } from "tsup";
import { writeFileSync, readFileSync } from "fs";
import { join } from "path";

// Entry points that contain client-side React hooks and need "use client" directive
const clientEntryNames = new Set([
  "animated-dialog",
  "dynamic-icon",
  "social-link-icon",
  "payment-platform-icon",
  "carousel-pagination",

  "pressable",
  "hooks",
  "use-navigation",
  "use-responsive-layout",
  "image-slider",
  "media-hover-ctas",
  "cta-documentation-links",
  "cta-feature-checklist",
  "cta-split-image",
  "cta-stacked-cards",
  "cta-feature-list",
  "cta-split-image-logos",
  "cta-fullwidth-background",
  "cta-feature-cards-grid",
  "cta-accent-background",
  "cta-split-gradient-image",
  "cta-background-icon-badge",
  "cta-pattern-background",
  "cta-platform-demo",
  "cta-enterprise-split",
  "cta-minimal-separator",
  "cta-image-overlay-arrow",
  "cta-app-download-newsletter",
  "cta-newsletter-features",
  "cta-hero-feature-cards",
  "cta-enterprise-dark-features",
  "cta-gradient-logos-floating",
  "cta-gradient-stats-hero",
  "cta-video-background-hero",
  "cta-workflow-tabs",
  "cta-case-study-testimonial",
  "cta-simple-centered",
  "feature-showcase",
  "feature-split-image",
  "feature-split-image-reverse",
  "feature-icon-grid-bordered",
  "feature-checklist-image",
  "feature-carousel-progress",
  "feature-card-grid-linked",
  "feature-numbered-cards",
  "feature-icon-grid-accent",
  "feature-three-column-values",
  "feature-badge-grid-six",
  "feature-pattern-grid-links",
  "feature-tabbed-content-image",
  "feature-utility-cards-grid",
  "feature-bento-utilities",
  "feature-checklist-three-column",
  "feature-integration-cards",
  "feature-icon-tabs-content",
  "feature-image-overlay-badge",
  "feature-category-image-cards",
  "feature-bento-image-grid",
  "feature-image-cards-three-column",
  "feature-icon-grid-muted",
  "feature-stats-highlight",
  "feature-accordion-image",
  "feature-animated-carousel",
  "team-media-showcase",
  "team-alternating-bios",
  "team-avatar-social",
  "team-bio-badges",
  "team-carousel-experience",
  "team-compact-cta",
  "team-compact-grid",
  "team-contact-cards",
  "team-department-sections",
  "team-expertise-cards",
  "team-filterable-search",
  "team-gradient-cards",
  "team-grid-animated",
  "team-hover-highlight",
  "team-hover-overlay",
  "team-investor-showcase",
  "team-large-images",
  "team-role-filter",
  "team-simple-grid",
  "team-skill-badges",
  "team-social-cards",
  "team-social-grid",
  "team-testimonial-stats",
  "footer-accordion-social",
  "footer-animated-social",
  "footer-background-card",
  "footer-brand-description",
  "footer-contact-card",
  "footer-cta-banner",
  "footer-cta-social",
  "footer-info-cards-accordion",
  "footer-links-grid",
  "footer-nav-social",
  "footer-newsletter-contact",
  "footer-newsletter-grid",
  "footer-newsletter-minimal",
  "footer-simple-centered",
  "footer-social-apps",
  "footer-social-newsletter",
  "footer-split-image-accordion",
  "expandable-case-study-cards",
  "carousel-badge-cards",
  "carousel-gradient-overlay",
  "carousel-demo-link",
  "auto-scroll-carousel",
  "carousel-sidebar-resources",
  "carousel-icon-tabs",
  "testimonial-carousel-cards",
  "carousel-icon-sidebar",
  "carousel-gradient-text",
  "service-hover-carousel",
  "carousel-tabs-content",
  "carousel-scale-focus",
  "carousel-animated-sections",
  "carousel-autoplay-progress",
  "carousel-auto-progress-slides",
  "carousel-feature-badge",
  "carousel-fullscreen-scroll-fx",
  "carousel-gallery-thumbnails",
  "carousel-horizontal-cards",
  "carousel-image-hero",
  "carousel-multi-step-showcase",
  "carousel-portfolio-hero",
  "carousel-product-feature-showcase",
  "carousel-progress-slider",
  "carousel-scrolling-feature-showcase",
  "masonry-motion-grid",
  "blur-vignette-grid",
  "interior-carousel",
  "project-detail-architecture-carousel",
  "project-detail-card-header",
  "project-detail-case-study-prose",
  "project-detail-compact-metadata",
  "project-detail-exhibition-sidebar",
  "project-detail-fashion-editorial",
  "project-detail-fullscreen-hero",
  "project-detail-grid-gallery",
  "project-detail-hero-metadata",
  "project-detail-hover-gallery",
  "project-detail-large-hero-featured",
  "project-detail-list-related",
  "project-detail-mask-reveal",
  "project-detail-minimal-centered",
  "project-detail-numbered-sections",
  "project-detail-parallax-scroll",
  "project-detail-photography-breadcrumb",
  "project-detail-sculpture-showcase",
  "project-detail-sidebar-navigation",
  "project-detail-sidebar-sticky",
  "project-detail-split-materials",
  "project-detail-tabbed-case-study",
  "resource-detail-whitepaper-sidebar",
  "resource-detail-article-hero",
  "resource-detail-document-sidebar",
  "about-mission-features",
  "about-stats-showcase",
  "about-company-profile",
  "about-culture-tabs",
  "about-vision-gallery",
  "about-developer-story",
  "about-story-gallery",
  "about-streamline-team",
  "about-developer-profile",
  "about-expandable-values",
  "about-startup-team",
  "about-minimal-story",
  "about-story-hero",
  "about-stats-sidebar",
  "about-interactive-tabs",
  "about-mission-principles",
  "about-mission-dual-image",
  "about-split-hero",
  "radial-gradient-top",
  "radial-gradient-bottom",
  "grid-basic",
  "grid-fade-top-left",
  "grid-fade-top-right",
  "grid-fade-top",
  "grid-fade-bottom",
  "grid-fade-bottom-left",
  "grid-fade-bottom-right",
  "grid-fade-center",
  "diagonal-cross-basic",
  "diagonal-cross-fade-top-left",
  "diagonal-cross-fade-top-right",
  "diagonal-cross-fade-top",
  "diagonal-cross-fade-bottom",
  "diagonal-cross-fade-bottom-left",
  "diagonal-cross-fade-bottom-right",
  "diagonal-cross-fade-center",
  "dashed-grid-basic",
  "dashed-grid-fade-top-left",
  "dashed-grid-fade-top-right",
  "dashed-grid-fade-top",
  "dashed-grid-fade-bottom",
  "dashed-grid-fade-bottom-left",
  "dashed-grid-fade-bottom-right",
  "dashed-grid-fade-center",
  "gradient-glow-top",
  "gradient-glow-bottom",
  "spotlight-left",
  "spotlight-right",
  "circuit-board-basic",
  "circuit-board-fade-top-left",
  "circuit-board-fade-top-right",
  "circuit-board-fade-top",
  "circuit-board-fade-bottom",
  "circuit-board-fade-bottom-left",
  "circuit-board-fade-bottom-right",
  "circuit-board-fade-center",
  "grid-dots-basic",
  "grid-dots-fade-center",
  "blog-grid-author-cards",
  "blog-cards-tagline-cta",
  "blog-cards-read-time",
  "blog-carousel-apple",
  "blog-category-overlay",
  "blog-featured-popular",
  "blog-related-articles",
  "blog-tech-insights",
  "blog-horizontal-cards",
  "blog-filtered-results",
  "blog-masonry-featured",
  "blog-horizontal-timeline",
  "blog-grid-nine-posts",
  "article-hero-prose",
  "article-sidebar-sticky",
  "article-toc-sidebar",
  "article-breadcrumb-social",
  "article-compact-toc",
  "article-chapters-author",
  "article-split-animated",
  "faq-simple-accordion",
  "faq-static-list",
  "faq-centered-accordion",
  "faq-badge-support",
  "faq-numbered-list",
  "faq-numbered-grid",
  "faq-split-help",
  "faq-categorized-sections",
  "faq-muted-cards",
  "faq-bordered-badge",
  "faq-gradient-categories",
  "faq-sidebar-navigation",
  "faq-card-categories",
  "faq-icon-benefits",
  "faq-rounded-cards",
  "faq-profile-sidebar",
  "faq-split-hero",
  "hero-badge-image-split",
  "hero-image-left-content",
  "hero-image-slider",
  "hero-centered-image-grid",
  "hero-centered-screenshot",
  "hero-pattern-badge-logos",
  "hero-logo-centered-screenshot",
  "hero-pattern-logo-tech-stack",
  "hero-announcement-badge",
  "hero-tech-carousel",
  "hero-simple-centered-image",
  "hero-platform-features-grid",
  "hero-spiral-pattern-cards",
  "hero-split-spiral-shapes",
  "hero-split-geometric-shapes",
  "hero-community-survey-cta",
  "hero-marketplace-scattered-images",
  "hero-badge-shadow-overlay",
  "hero-video-background-dark",
  "hero-grid-pattern-efficiency",
  "hero-dashed-border-features",
  "hero-design-carousel-portfolio",
  "hero-gradient-client-focused",
  "hero-premium-split-avatars",
  "hero-ui-library-showcase",
  "hero-fullscreen-background-image",
  "hero-fullscreen-logo-cta",
  "hero-gradient-avatars-rating",
  "hero-task-timer-animated",
  "hero-ai-powered-carousel",
  "hero-ad-campaign-expert",
  "hero-adaptable-product-grid",
  "hero-presentation-platform-video",
  "hero-grid-pattern-solutions",
  "hero-crm-streamlined",
  "hero-billing-platform-logos",
  "hero-software-growth-video-dialog",
  "hero-conversion-video-play",
  "hero-design-showcase-logos",
  "hero-video-overlay-stars",
  "hero-productivity-launcher-video",
  "hero-hiring-animated-text",
  "hero-split-image-newsletter",
  "hero-centered-gradient-cta",
  "hero-stats-social-proof",
  "hero-feature-cards-grid",
  "hero-testimonial-image-grid",
  "hero-design-system-3d",
  "hero-architecture-fullscreen",
  "hero-innovation-image-grid",
  "hero-video-dialog-gradient",
  "hero-minimal-centered-dark",
  "hero-product-showcase-floating",
  "hero-saas-dashboard-preview",
  "hero-therapy-testimonial-grid",
  "hero-mental-health-team",
  "hero-mentorship-video-split",
  "hero-business-operations-mosaic",
  "hero-agency-animated-images",
  "hero-welcome-asymmetric-images",
  "hero-startup-launch-cta",
  "hero-enterprise-security",
  "hero-creative-studio-stacked",
  "hero-digital-agency-fullscreen",
  "hero-customer-support-layered",
  "hero-shared-inbox-layered",
  "hero-conversation-intelligence",
  "hero-business-carousel-dots",
  "hero-developer-tools-code",
  "hero-ecommerce-product-showcase",
  "hero-mobile-app-download",
  "hero-pricing-comparison",
  "hero-newsletter-minimal",
  "hero-coming-soon-countdown",
  "hero-event-registration",
  "hero-portfolio-creative",
  "case-studies-image-grid",
  "case-studies-testimonial-stats",
  "case-studies-featured-border",
  "case-studies-stats-card",
  "case-study-prose-sidebar",
  "case-study-toc-social-sidebar",
  "case-study-stats-metrics",
  "comparison-table-two-column",
  "comparison-feature-cards",
  "comparison-grid-badges",
  "comparison-metrics-rows",
  "comparison-image-cards",
  "comparison-table-tabs",
  "comparison-table-tooltips",
  "comparison-feature-grid",
  "comparison-ai-models",
  "comparison-legacy-modern",
  "navbar-dropdown-menu",
  "navbar-centered-menu",
  "navbar-mega-menu",
  "navbar-enterprise-mega",
  "navbar-feature-grid",
  "navbar-floating-pill",
  "navbar-platform-resources",
  "navbar-image-preview",
  "navbar-dark-icons",
  "navbar-animated-preview",
  "navbar-multi-column-groups",
  "navbar-sidebar-mobile",
  "navbar-transparent-overlay",
  "navbar-education-platform",
  "navbar-sticky-compact",
  "navbar-search-focused",
  "navbar-simple-links",
  "navbar-split-cta",
  "navbar-icon-links",
  "navbar-tabbed-sections",
  "navbar-fullscreen-menu",
  "logos-inline-tagline",
  "logos-certifications-grid",
  "logos-carousel-heading",
  "logos-partner-network",
  "logos-two-row-grid",
  "logos-marquee-muted",
  "logos-centered-simple",
  "logos-numbered-carousel",
  "logos-double-carousel-pattern",
  "logos-minimal-carousel",
  "logos-partner-grid-sidebar",
  "process-sticky-steps",
  "process-scroll-image",
  "process-hover-cards",
  "process-icon-timeline",
  "process-expandable-timeline",
  "process-roadmap-timeline",
  "process-mission-principles",
  "process-steps-grid",
  "process-numbered-services",
  "project-alternating-motion",
  "project-background-reveal",
  "project-card-overlay",
  "project-carousel-cinematic",
  "project-carousel-detail-cards",
  "project-carousel-minimal",
  "project-experience-quote",
  "project-featured-carousel",
  "project-filterable-gallery",
  "project-filterable-three-column",
  "project-grid-gallery",
  "project-grid-motion",
  "project-horizontal-cards",
  "project-hover-reveal-grid",
  "project-interactive-hover-reveal",
  "project-masonry-columns",
  "project-nature-mosaic",
  "project-scroll-reveal",
  "project-showcase-alternating",
  "project-sticky-scroll",
  "project-studio-hover-preview",
  "project-table-list",
  "project-video-carousel",
  "project-video-hover-bento",
  "project-video-hover-grid",
  "project-video-hover-rounded",
  "project-video-hover-stack",
  "project-video-hover-two-by-two",
  "project-work-showcase",
  "project-zigzag-layout",
  "banner-promo-cta",
  "banner-countdown-sale",
  "banner-delivery-countdown",
  "banner-announcement-dismissible",
  "banner-privacy-notice",
  "banner-survey-incentive",
  "banner-social-follow",
  "banner-gdpr-rights",
  "banner-event-promo",
  "banner-floating-offer",
  "industries-hover-reveal-grid",
  "industries-badge-list-bordered",
  "industries-timeline-table",
  "industries-expandable-showcase",
  "testimonials-list-verified",
  "testimonials-images-helpful",
  "testimonials-bento-grid",
  "testimonials-twitter-cards",
  "testimonials-carousel-image",
  "testimonials-centered-avatars",
  "testimonials-company-logo",
  "testimonials-grid-add-review",
  "testimonials-marquee",
  "testimonials-simple-grid",
  "testimonials-slider-minimal",
  "testimonials-split-image",
  "testimonials-stats-header",
  "testimonials-wall-compact",
  "testimonials-mini-dividers",
  "testimonials-logo-cards",
  "testimonials-quote-carousel",
  "testimonials-animated-split",
  "testimonials-scrolling-columns",
  "testimonials-minimal-numbered",
  "testimonials-parallax-number",
  "testimonials-masonry-grid",
  "testimonials-large-quote",
  "service-detail-prose-minimal",
  "service-detail-image-hero",
  "service-detail-stats-hero",
  "service-detail-sidebar-stats",
  "service-detail-sidebar-related",
  "service-detail-centered-expertise",
  "service-detail-compact-cards",
  "resource-list-hero-filter",
  "resource-list-featured-grid",
  "resource-list-featured-articles",
  "resource-list-news-updates",
  "resource-list-course-cards",
  "stats-simple-grid",
  "stats-icon-cards",
  "stats-timeline-tabs",
  "stats-primary-secondary",
  "stats-growth-timeline",
  "stats-impact-grid",
  "stats-circular-progress",
  "stats-card-group",
  "stats-animated-counter",
  "stats-number-ticker",
  "stats-milestone-sidebar",
  "stats-bar-comparison",
  "link-tree-block",
  "link-page-minimal-profile",
  "link-page-newsletter-social",
  "link-page-grid-cards",
  "link-page-bento-layout",
  "timeline-vertical-icon-dashed",
  "timeline-scroll-sticky-image",
  "timeline-two-column-featured",
  "timeline-alternating-diagonal",
  "timeline-ai-workflow-cards",
  "timeline-productivity-list",
  "timeline-stepper-animated",
  "timeline-changelog-badges",
  "timeline-history-prose",
  "timeline-horizontal-phases",
  "timeline-horizontal-icons",
  "timeline-tabbed-phases",
  "timeline-product-launch",
  "timeline-scroll-highlight",
  "about-location-info-hero",
  "about-network-spotlight",
  "about-story-expertise",
  "community-initiatives",
  "contact-callback",
  "contact-card",
  "contact-careers",
  "contact-catering",
  "contact-consultation",
  "contact-dark",
  "contact-demo",
  "contact-emergency",
  "contact-event",
  "contact-faq",
  "contact-feedback",
  "contact-fitness",
  "contact-floating-banner",
  "contact-guest",
  "contact-help-center",
  "contact-image",
  "contact-insurance",
  "contact-interview",
  "contact-locations",
  "contact-maintenance",
  "contact-map",
  "contact-minimal",
  "contact-moving",
  "contact-multistep",
  "contact-partnership",
  "contact-photography",
  "contact-press",
  "contact-quote",
  "contact-referral",
  "contact-report",
  "contact-reservation",
  "contact-retreat",
  "contact-rsvp",
  "contact-sales",
  "contact-schedule",
  "contact-sponsorship",
  "contact-support",
  "contact-tenant",
  "contact-vendor",
  "contact-volunteer",
  "contact-warranty",
  "contact-wedding",
  "cta-image-overlay-centered",
  "feature-capabilities-grid",
  "footer-brand-links-contact",
  "footer-comprehensive-links",
  "hero-floating-images",
  "hero-overlay-cta-grid",
  "hero-split-icon-cards",
  "list-achievements-showcase",
  "list-career-timeline",
  "list-feature-comparison",
  "list-metrics-dashboard",
  "list-searchable-grid",
  "list-service-category-table",
  "offer-modal-membership-image",
  "offer-modal-newsletter-discount",
  "offer-modal-sheet-newsletter",
  "pricing-addons-cards",
  "pricing-addons-featured",
  "pricing-collapsible-plans",
  "pricing-columns-toggle",
  "pricing-comparison-headers",
  "pricing-comparison-table",
  "pricing-discount-card",
  "pricing-enterprise-contact",
  "pricing-feature-matrix",
  "pricing-four-tier-toggle",
  "pricing-full-comparison",
  "pricing-gradient-cards",
  "pricing-icon-headers",
  "pricing-minimal-cards",
  "pricing-packages-radio",
  "pricing-popular-highlight",
  "pricing-radio-toggle",
  "pricing-responsive-table",
  "pricing-services-cards",
  "pricing-simple-card",
  "pricing-single-card",
  "pricing-split-layout",
  "pricing-spotlight-card",
  "pricing-switch-cards",
  "pricing-tabs-toggle",
  "pricing-tier-grid",
  "pricing-toggle-cards",
  "pricing-toggle-period",
  "pricing-two-column-basic",
  "services-list-feature-spotlight",
  "services-list-accordion",
  "services-list-accordion-benefits",
  "services-list-cards-hover",
  "services-list-category-accordion",
  "services-list-centered-icons",
  "services-list-culture-tabs",
  "services-list-expandable-cards",
  "services-list-featured-highlight",
  "services-list-hero-cards",
  "services-list-icon-grid",
  "services-list-image-cards",
  "services-list-image-overlay-grid",
  "services-list-masonry",
  "services-list-methodology-steps",
  "services-list-minimal-grid",
  "services-list-muted-cards",
  "services-list-numbered-steps",
  "services-list-pricing-grid",
  "services-list-progress-sidebar",
  "services-list-split-checklist",
  "services-list-sticky-image",
  "services-list-table-hover",
  "services-list-tabs-features",
  "services-list-timeline",
  "services-list-two-column-grid",
  "services-list-vertical-tags",
  "services-list-video-showcase",
  "components",
  "index",
  "longform-content",
]);

// Shared configuration
// Source maps are disabled by default to reduce NPM package size from ~128MB to ~65MB
// Set GENERATE_SOURCEMAPS=true to enable source maps for debugging
const sharedConfig: Partial<Options> = {
  format: ["esm", "cjs"],
  dts: true,
  splitting: false,
  sourcemap: process.env.GENERATE_SOURCEMAPS === "true",
  treeshake: true,
  minify: false,
  external: [
    "react",
    "react-dom",
    "framer-motion",
    "@opensite/hooks",
    "valibot",
    "@page-speed/router",
    "@page-speed/pressable",
  ],
};

// All entries
const allEntries = {
  index: "src/index.ts",
  components: "src/components.ts",
  container: "components/ui/container.tsx",
  section: "components/ui/section.tsx",
  "animated-dialog": "components/ui/animated-dialog.tsx",
  "page-hero-banner": "components/ui/page-hero-banner.tsx",
  "image-slider": "components/ui/image-slider.tsx",
  "aspect-ratio": "components/ui/aspect-ratio.tsx",
  "media-aspect-ratio": "components/ui/media-aspect-ratio.tsx",
  button: "components/ui/button.tsx",
  card: "components/ui/card.tsx",
  badge: "components/ui/badge.tsx",
  popover: "components/ui/popover.tsx",
  "dynamic-icon": "components/ui/dynamic-icon.tsx",
  "social-link-icon": "components/ui/social-link-icon.tsx",
  "payment-platform-icon": "components/ui/payment-platform-icon.tsx",
  "carousel-pagination": "components/ui/carousel-pagination.tsx",
  pressable: "lib/Pressable.tsx",
  hooks: "lib/hooks.ts",
  "longform-content": "src/longform-content.ts",
  "use-navigation": "lib/useNavigation.ts",
  "use-responsive-layout": "lib/useResponsiveLayout.ts",
  "alternating-blocks": "src/alternating-blocks.ts",
  "media-hover-ctas": "src/media-hover-ctas.ts",
  "cta-documentation-links": "src/cta-documentation-links.ts",
  "cta-feature-checklist": "src/cta-feature-checklist.ts",
  "cta-split-image": "src/cta-split-image.ts",
  "cta-stacked-cards": "src/cta-stacked-cards.ts",
  "cta-feature-list": "src/cta-feature-list.ts",
  "cta-split-image-logos": "src/cta-split-image-logos.ts",
  "cta-fullwidth-background": "src/cta-fullwidth-background.ts",
  "cta-feature-cards-grid": "src/cta-feature-cards-grid.ts",
  "cta-accent-background": "src/cta-accent-background.ts",
  "cta-split-gradient-image": "src/cta-split-gradient-image.ts",
  "cta-background-icon-badge": "src/cta-background-icon-badge.ts",
  "cta-pattern-background": "src/cta-pattern-background.ts",
  "cta-platform-demo": "src/cta-platform-demo.ts",
  "cta-enterprise-split": "src/cta-enterprise-split.ts",
  "cta-minimal-separator": "src/cta-minimal-separator.ts",
  "cta-image-overlay-arrow": "src/cta-image-overlay-arrow.ts",
  "cta-app-download-newsletter": "src/cta-app-download-newsletter.ts",
  "cta-newsletter-features": "src/cta-newsletter-features.ts",
  "cta-hero-feature-cards": "src/cta-hero-feature-cards.ts",
  "cta-enterprise-dark-features": "src/cta-enterprise-dark-features.ts",
  "cta-gradient-logos-floating": "src/cta-gradient-logos-floating.ts",
  "cta-gradient-stats-hero": "src/cta-gradient-stats-hero.ts",
  "cta-video-background-hero": "src/cta-video-background-hero.ts",
  "cta-workflow-tabs": "src/cta-workflow-tabs.ts",
  "cta-case-study-testimonial": "src/cta-case-study-testimonial.ts",
  "cta-simple-centered": "src/cta-simple-centered.ts",
  "feature-showcase": "src/feature-showcase.ts",
  "feature-split-image": "src/feature-split-image.ts",
  "feature-split-image-reverse": "src/feature-split-image-reverse.ts",
  "feature-icon-grid-bordered": "src/feature-icon-grid-bordered.ts",
  "feature-checklist-image": "src/feature-checklist-image.ts",
  "feature-carousel-progress": "src/feature-carousel-progress.ts",
  "feature-card-grid-linked": "src/feature-card-grid-linked.ts",
  "feature-numbered-cards": "src/feature-numbered-cards.ts",
  "feature-icon-grid-accent": "src/feature-icon-grid-accent.ts",
  "feature-three-column-values": "src/feature-three-column-values.ts",
  "feature-badge-grid-six": "src/feature-badge-grid-six.ts",
  "feature-pattern-grid-links": "src/feature-pattern-grid-links.ts",
  "feature-tabbed-content-image": "src/feature-tabbed-content-image.ts",
  "feature-utility-cards-grid": "src/feature-utility-cards-grid.ts",
  "feature-bento-utilities": "src/feature-bento-utilities.ts",
  "feature-checklist-three-column": "src/feature-checklist-three-column.ts",
  "feature-integration-cards": "src/feature-integration-cards.ts",
  "feature-icon-tabs-content": "src/feature-icon-tabs-content.ts",
  "feature-image-overlay-badge": "src/feature-image-overlay-badge.ts",
  "feature-category-image-cards": "src/feature-category-image-cards.ts",
  "feature-bento-image-grid": "src/feature-bento-image-grid.ts",
  "feature-image-cards-three-column": "src/feature-image-cards-three-column.ts",
  "feature-icon-grid-muted": "src/feature-icon-grid-muted.ts",
  "feature-stats-highlight": "src/feature-stats-highlight.ts",
  "feature-accordion-image": "src/feature-accordion-image.ts",
  "feature-animated-carousel": "src/feature-animated-carousel.ts",
  "team-media-showcase": "src/team-media-showcase.ts",
  "team-alternating-bios": "src/team-alternating-bios.ts",
  "team-avatar-social": "src/team-avatar-social.ts",
  "team-bio-badges": "src/team-bio-badges.ts",
  "team-carousel-experience": "src/team-carousel-experience.ts",
  "team-compact-cta": "src/team-compact-cta.ts",
  "team-compact-grid": "src/team-compact-grid.ts",
  "team-contact-cards": "src/team-contact-cards.ts",
  "team-department-sections": "src/team-department-sections.ts",
  "team-expertise-cards": "src/team-expertise-cards.ts",
  "team-filterable-search": "src/team-filterable-search.ts",
  "team-gradient-cards": "src/team-gradient-cards.ts",
  "team-grid-animated": "src/team-grid-animated.ts",
  "team-hover-highlight": "src/team-hover-highlight.ts",
  "team-hover-overlay": "src/team-hover-overlay.ts",
  "team-investor-showcase": "src/team-investor-showcase.ts",
  "team-large-images": "src/team-large-images.ts",
  "team-role-filter": "src/team-role-filter.ts",
  "team-simple-grid": "src/team-simple-grid.ts",
  "team-skill-badges": "src/team-skill-badges.ts",
  "team-social-cards": "src/team-social-cards.ts",
  "team-social-grid": "src/team-social-grid.ts",
  "team-testimonial-stats": "src/team-testimonial-stats.ts",
  "footer-accordion-social": "src/footer-accordion-social.ts",
  "footer-animated-social": "src/footer-animated-social.ts",
  "footer-background-card": "src/footer-background-card.ts",
  "footer-brand-description": "src/footer-brand-description.ts",
  "footer-contact-card": "src/footer-contact-card.ts",
  "footer-cta-banner": "src/footer-cta-banner.ts",
  "footer-cta-social": "src/footer-cta-social.ts",
  "footer-info-cards-accordion": "src/footer-info-cards-accordion.ts",
  "footer-links-grid": "src/footer-links-grid.ts",
  "footer-nav-social": "src/footer-nav-social.ts",
  "footer-newsletter-contact": "src/footer-newsletter-contact.ts",
  "footer-newsletter-grid": "src/footer-newsletter-grid.ts",
  "footer-newsletter-minimal": "src/footer-newsletter-minimal.ts",
  "footer-simple-centered": "src/footer-simple-centered.ts",
  "footer-social-apps": "src/footer-social-apps.ts",
  "footer-social-newsletter": "src/footer-social-newsletter.ts",
  "footer-split-image-accordion": "src/footer-split-image-accordion.ts",
  "expandable-case-study-cards": "src/expandable-case-study-cards.ts",
  "carousel-badge-cards": "src/carousel-badge-cards.ts",
  "carousel-gradient-overlay": "src/carousel-gradient-overlay.ts",
  "carousel-demo-link": "src/carousel-demo-link.ts",
  "auto-scroll-carousel": "src/auto-scroll-carousel.ts",
  "carousel-sidebar-resources": "src/carousel-sidebar-resources.ts",
  "carousel-icon-tabs": "src/carousel-icon-tabs.ts",
  "testimonial-carousel-cards": "src/testimonial-carousel-cards.ts",
  "carousel-icon-sidebar": "src/carousel-icon-sidebar.ts",
  "carousel-gradient-text": "src/carousel-gradient-text.ts",
  "service-hover-carousel": "src/service-hover-carousel.ts",
  "carousel-tabs-content": "src/carousel-tabs-content.ts",
  "carousel-scale-focus": "src/carousel-scale-focus.ts",
  "carousel-animated-sections": "src/carousel-animated-sections.ts",
  "carousel-autoplay-progress": "src/carousel-autoplay-progress.ts",
  "carousel-auto-progress-slides": "src/carousel-auto-progress-slides.ts",
  "carousel-feature-badge": "src/carousel-feature-badge.ts",
  "carousel-fullscreen-scroll-fx": "src/carousel-fullscreen-scroll-fx.ts",
  "carousel-gallery-thumbnails": "src/carousel-gallery-thumbnails.ts",
  "carousel-horizontal-cards": "src/carousel-horizontal-cards.ts",
  "carousel-image-hero": "src/carousel-image-hero.ts",
  "carousel-multi-step-showcase": "src/carousel-multi-step-showcase.ts",
  "carousel-portfolio-hero": "src/carousel-portfolio-hero.ts",
  "carousel-product-feature-showcase":
    "src/carousel-product-feature-showcase.ts",
  "carousel-progress-slider": "src/carousel-progress-slider.ts",
  "carousel-scrolling-feature-showcase":
    "src/carousel-scrolling-feature-showcase.ts",
  "masonry-motion-grid": "src/masonry-motion-grid.ts",
  "blur-vignette-grid": "src/blur-vignette-grid.ts",
  "interior-carousel": "src/interior-carousel.ts",
  "about-mission-features": "src/about-mission-features.ts",
  "about-stats-showcase": "src/about-stats-showcase.ts",
  "about-company-profile": "src/about-company-profile.ts",
  "about-culture-tabs": "src/about-culture-tabs.ts",
  "about-vision-gallery": "src/about-vision-gallery.ts",
  "about-developer-story": "src/about-developer-story.ts",
  "about-story-gallery": "src/about-story-gallery.ts",
  "about-streamline-team": "src/about-streamline-team.ts",
  "about-developer-profile": "src/about-developer-profile.ts",
  "about-expandable-values": "src/about-expandable-values.ts",
  "about-startup-team": "src/about-startup-team.ts",
  "about-minimal-story": "src/about-minimal-story.ts",
  "about-story-hero": "src/about-story-hero.ts",
  "about-stats-sidebar": "src/about-stats-sidebar.ts",
  "about-interactive-tabs": "src/about-interactive-tabs.ts",
  "about-mission-principles": "src/about-mission-principles.ts",
  "about-mission-dual-image": "src/about-mission-dual-image.ts",
  "radial-gradient-top": "src/radial-gradient-top.ts",
  "radial-gradient-bottom": "src/radial-gradient-bottom.ts",
  "grid-basic": "src/grid-basic.ts",
  "grid-fade-top-left": "src/grid-fade-top-left.ts",
  "grid-fade-top-right": "src/grid-fade-top-right.ts",
  "grid-fade-top": "src/grid-fade-top.ts",
  "grid-fade-bottom": "src/grid-fade-bottom.ts",
  "grid-fade-bottom-left": "src/grid-fade-bottom-left.ts",
  "grid-fade-bottom-right": "src/grid-fade-bottom-right.ts",
  "grid-fade-center": "src/grid-fade-center.ts",
  "diagonal-cross-basic": "src/diagonal-cross-basic.ts",
  "diagonal-cross-fade-top-left": "src/diagonal-cross-fade-top-left.ts",
  "diagonal-cross-fade-top-right": "src/diagonal-cross-fade-top-right.ts",
  "diagonal-cross-fade-top": "src/diagonal-cross-fade-top.ts",
  "diagonal-cross-fade-bottom": "src/diagonal-cross-fade-bottom.ts",
  "diagonal-cross-fade-bottom-left": "src/diagonal-cross-fade-bottom-left.ts",
  "diagonal-cross-fade-bottom-right": "src/diagonal-cross-fade-bottom-right.ts",
  "diagonal-cross-fade-center": "src/diagonal-cross-fade-center.ts",
  "dashed-grid-basic": "src/dashed-grid-basic.ts",
  "dashed-grid-fade-top-left": "src/dashed-grid-fade-top-left.ts",
  "dashed-grid-fade-top-right": "src/dashed-grid-fade-top-right.ts",
  "dashed-grid-fade-top": "src/dashed-grid-fade-top.ts",
  "dashed-grid-fade-bottom": "src/dashed-grid-fade-bottom.ts",
  "dashed-grid-fade-bottom-left": "src/dashed-grid-fade-bottom-left.ts",
  "dashed-grid-fade-bottom-right": "src/dashed-grid-fade-bottom-right.ts",
  "dashed-grid-fade-center": "src/dashed-grid-fade-center.ts",
  "gradient-glow-top": "src/gradient-glow-top.ts",
  "gradient-glow-bottom": "src/gradient-glow-bottom.ts",
  "spotlight-left": "src/spotlight-left.ts",
  "spotlight-right": "src/spotlight-right.ts",
  "circuit-board-basic": "src/circuit-board-basic.ts",
  "circuit-board-fade-top-left": "src/circuit-board-fade-top-left.ts",
  "circuit-board-fade-top-right": "src/circuit-board-fade-top-right.ts",
  "circuit-board-fade-top": "src/circuit-board-fade-top.ts",
  "circuit-board-fade-bottom": "src/circuit-board-fade-bottom.ts",
  "circuit-board-fade-bottom-left": "src/circuit-board-fade-bottom-left.ts",
  "circuit-board-fade-bottom-right": "src/circuit-board-fade-bottom-right.ts",
  "circuit-board-fade-center": "src/circuit-board-fade-center.ts",
  "grid-dots-basic": "src/grid-dots-basic.ts",
  "grid-dots-fade-center": "src/grid-dots-fade-center.ts",
  "blog-grid-author-cards": "src/blog-grid-author-cards.ts",
  "blog-cards-tagline-cta": "src/blog-cards-tagline-cta.ts",
  "blog-cards-read-time": "src/blog-cards-read-time.ts",
  "blog-carousel-apple": "src/blog-carousel-apple.ts",
  "blog-category-overlay": "src/blog-category-overlay.ts",
  "blog-featured-popular": "src/blog-featured-popular.ts",
  "blog-related-articles": "src/blog-related-articles.ts",
  "blog-tech-insights": "src/blog-tech-insights.ts",
  "blog-horizontal-cards": "src/blog-horizontal-cards.ts",
  "blog-filtered-results": "src/blog-filtered-results.ts",
  "blog-masonry-featured": "src/blog-masonry-featured.ts",
  "blog-horizontal-timeline": "src/blog-horizontal-timeline.ts",
  "blog-grid-nine-posts": "src/blog-grid-nine-posts.ts",
  "article-hero-prose": "src/article-hero-prose.ts",
  "article-sidebar-sticky": "src/article-sidebar-sticky.ts",
  "article-toc-sidebar": "src/article-toc-sidebar.ts",
  "article-breadcrumb-social": "src/article-breadcrumb-social.ts",
  "article-compact-toc": "src/article-compact-toc.ts",
  "article-chapters-author": "src/article-chapters-author.ts",
  "article-split-animated": "src/article-split-animated.ts",
  "faq-simple-accordion": "src/faq-simple-accordion.ts",
  "faq-static-list": "src/faq-static-list.ts",
  "faq-centered-accordion": "src/faq-centered-accordion.ts",
  "faq-badge-support": "src/faq-badge-support.ts",
  "faq-numbered-list": "src/faq-numbered-list.ts",
  "faq-numbered-grid": "src/faq-numbered-grid.ts",
  "faq-split-help": "src/faq-split-help.ts",
  "faq-categorized-sections": "src/faq-categorized-sections.ts",
  "faq-muted-cards": "src/faq-muted-cards.ts",
  "faq-bordered-badge": "src/faq-bordered-badge.ts",
  "faq-gradient-categories": "src/faq-gradient-categories.ts",
  "faq-sidebar-navigation": "src/faq-sidebar-navigation.ts",
  "faq-card-categories": "src/faq-card-categories.ts",
  "faq-icon-benefits": "src/faq-icon-benefits.ts",
  "faq-rounded-cards": "src/faq-rounded-cards.ts",
  "faq-profile-sidebar": "src/faq-profile-sidebar.ts",
  "faq-split-hero": "src/faq-split-hero.ts",
  "hero-badge-image-split": "src/hero-badge-image-split.ts",
  "hero-image-left-content": "src/hero-image-left-content.ts",
  "hero-image-slider": "src/hero-image-slider.ts",
  "hero-centered-image-grid": "src/hero-centered-image-grid.ts",
  "hero-centered-screenshot": "src/hero-centered-screenshot.ts",
  "hero-pattern-badge-logos": "src/hero-pattern-badge-logos.ts",
  "hero-logo-centered-screenshot": "src/hero-logo-centered-screenshot.ts",
  "hero-pattern-logo-tech-stack": "src/hero-pattern-logo-tech-stack.ts",
  "hero-announcement-badge": "src/hero-announcement-badge.ts",
  "hero-tech-carousel": "src/hero-tech-carousel.ts",
  "hero-simple-centered-image": "src/hero-simple-centered-image.ts",
  "hero-platform-features-grid": "src/hero-platform-features-grid.ts",
  "hero-spiral-pattern-cards": "src/hero-spiral-pattern-cards.ts",
  "hero-split-spiral-shapes": "src/hero-split-spiral-shapes.ts",
  "hero-split-geometric-shapes": "src/hero-split-geometric-shapes.ts",
  "hero-community-survey-cta": "src/hero-community-survey-cta.ts",
  "hero-marketplace-scattered-images":
    "src/hero-marketplace-scattered-images.ts",
  "hero-badge-shadow-overlay": "src/hero-badge-shadow-overlay.ts",
  "hero-video-background-dark": "src/hero-video-background-dark.ts",
  "hero-grid-pattern-efficiency": "src/hero-grid-pattern-efficiency.ts",
  "hero-dashed-border-features": "src/hero-dashed-border-features.ts",
  "hero-design-carousel-portfolio": "src/hero-design-carousel-portfolio.ts",
  "hero-gradient-client-focused": "src/hero-gradient-client-focused.ts",
  "hero-premium-split-avatars": "src/hero-premium-split-avatars.ts",
  "hero-ui-library-showcase": "src/hero-ui-library-showcase.ts",
  "hero-fullscreen-background-image": "src/hero-fullscreen-background-image.ts",
  "hero-fullscreen-logo-cta": "src/hero-fullscreen-logo-cta.ts",
  "hero-gradient-avatars-rating": "src/hero-gradient-avatars-rating.ts",
  "hero-task-timer-animated": "src/hero-task-timer-animated.ts",
  "hero-ai-powered-carousel": "src/hero-ai-powered-carousel.ts",
  "hero-ad-campaign-expert": "src/hero-ad-campaign-expert.ts",
  "hero-adaptable-product-grid": "src/hero-adaptable-product-grid.ts",
  "hero-presentation-platform-video": "src/hero-presentation-platform-video.ts",
  "hero-grid-pattern-solutions": "src/hero-grid-pattern-solutions.ts",
  "hero-crm-streamlined": "src/hero-crm-streamlined.ts",
  "hero-billing-platform-logos": "src/hero-billing-platform-logos.ts",
  "hero-software-growth-video-dialog":
    "src/hero-software-growth-video-dialog.ts",
  "hero-conversion-video-play": "src/hero-conversion-video-play.ts",
  "hero-design-showcase-logos": "src/hero-design-showcase-logos.ts",
  "hero-video-overlay-stars": "src/hero-video-overlay-stars.ts",
  "hero-productivity-launcher-video": "src/hero-productivity-launcher-video.ts",
  "hero-hiring-animated-text": "src/hero-hiring-animated-text.ts",
  "hero-split-image-newsletter": "src/hero-split-image-newsletter.ts",
  "hero-centered-gradient-cta": "src/hero-centered-gradient-cta.ts",
  "hero-stats-social-proof": "src/hero-stats-social-proof.ts",
  "hero-feature-cards-grid": "src/hero-feature-cards-grid.ts",
  "hero-testimonial-image-grid": "src/hero-testimonial-image-grid.ts",
  "hero-design-system-3d": "src/hero-design-system-3d.ts",
  "hero-architecture-fullscreen": "src/hero-architecture-fullscreen.ts",
  "hero-innovation-image-grid": "src/hero-innovation-image-grid.ts",
  "hero-video-dialog-gradient": "src/hero-video-dialog-gradient.ts",
  "hero-minimal-centered-dark": "src/hero-minimal-centered-dark.ts",
  "hero-product-showcase-floating": "src/hero-product-showcase-floating.ts",
  "hero-saas-dashboard-preview": "src/hero-saas-dashboard-preview.ts",
  "hero-therapy-testimonial-grid": "src/hero-therapy-testimonial-grid.ts",
  "hero-mental-health-team": "src/hero-mental-health-team.ts",
  "hero-mentorship-video-split": "src/hero-mentorship-video-split.ts",
  "hero-business-operations-mosaic": "src/hero-business-operations-mosaic.ts",
  "hero-agency-animated-images": "src/hero-agency-animated-images.ts",
  "hero-welcome-asymmetric-images": "src/hero-welcome-asymmetric-images.ts",
  "hero-startup-launch-cta": "src/hero-startup-launch-cta.ts",
  "hero-enterprise-security": "src/hero-enterprise-security.ts",
  "hero-creative-studio-stacked": "src/hero-creative-studio-stacked.ts",
  "hero-digital-agency-fullscreen": "src/hero-digital-agency-fullscreen.ts",
  "hero-customer-support-layered": "src/hero-customer-support-layered.ts",
  "hero-shared-inbox-layered": "src/hero-shared-inbox-layered.ts",
  "hero-conversation-intelligence": "src/hero-conversation-intelligence.ts",
  "hero-business-carousel-dots": "src/hero-business-carousel-dots.ts",
  "hero-developer-tools-code": "src/hero-developer-tools-code.ts",
  "hero-ecommerce-product-showcase": "src/hero-ecommerce-product-showcase.ts",
  "hero-mobile-app-download": "src/hero-mobile-app-download.ts",
  "hero-pricing-comparison": "src/hero-pricing-comparison.ts",
  "hero-newsletter-minimal": "src/hero-newsletter-minimal.ts",
  "hero-coming-soon-countdown": "src/hero-coming-soon-countdown.ts",
  "hero-event-registration": "src/hero-event-registration.ts",
  "hero-portfolio-creative": "src/hero-portfolio-creative.ts",
  "case-studies-image-grid": "src/case-studies-image-grid.ts",
  "case-studies-testimonial-stats": "src/case-studies-testimonial-stats.ts",
  "case-studies-featured-border": "src/case-studies-featured-border.ts",
  "case-studies-stats-card": "src/case-studies-stats-card.ts",
  "case-study-prose-sidebar": "src/case-study-prose-sidebar.ts",
  "case-study-toc-social-sidebar": "src/case-study-toc-social-sidebar.ts",
  "case-study-stats-metrics": "src/case-study-stats-metrics.ts",
  "comparison-table-two-column": "src/comparison-table-two-column.ts",
  "comparison-feature-cards": "src/comparison-feature-cards.ts",
  "comparison-grid-badges": "src/comparison-grid-badges.ts",
  "comparison-metrics-rows": "src/comparison-metrics-rows.ts",
  "comparison-image-cards": "src/comparison-image-cards.ts",
  "comparison-table-tabs": "src/comparison-table-tabs.ts",
  "comparison-table-tooltips": "src/comparison-table-tooltips.ts",
  "comparison-feature-grid": "src/comparison-feature-grid.ts",
  "comparison-ai-models": "src/comparison-ai-models.ts",
  "comparison-legacy-modern": "src/comparison-legacy-modern.ts",
  "navbar-dropdown-menu": "src/navbar-dropdown-menu.ts",
  "navbar-centered-menu": "src/navbar-centered-menu.ts",
  "navbar-mega-menu": "src/navbar-mega-menu.ts",
  "navbar-enterprise-mega": "src/navbar-enterprise-mega.ts",
  "navbar-feature-grid": "src/navbar-feature-grid.ts",
  "navbar-floating-pill": "src/navbar-floating-pill.ts",
  "navbar-platform-resources": "src/navbar-platform-resources.ts",
  "navbar-image-preview": "src/navbar-image-preview.ts",
  "navbar-dark-icons": "src/navbar-dark-icons.ts",
  "navbar-animated-preview": "src/navbar-animated-preview.ts",
  "navbar-multi-column-groups": "src/navbar-multi-column-groups.ts",
  "navbar-sidebar-mobile": "src/navbar-sidebar-mobile.ts",
  "navbar-transparent-overlay": "src/navbar-transparent-overlay.ts",
  "navbar-education-platform": "src/navbar-education-platform.ts",
  "navbar-sticky-compact": "src/navbar-sticky-compact.ts",
  "navbar-search-focused": "src/navbar-search-focused.ts",
  "navbar-simple-links": "src/navbar-simple-links.ts",
  "navbar-split-cta": "src/navbar-split-cta.ts",
  "navbar-icon-links": "src/navbar-icon-links.ts",
  "navbar-tabbed-sections": "src/navbar-tabbed-sections.ts",
  "navbar-fullscreen-menu": "src/navbar-fullscreen-menu.ts",
  "logos-inline-tagline": "src/logos-inline-tagline.ts",
  "logos-certifications-grid": "src/logos-certifications-grid.ts",
  "logos-carousel-heading": "src/logos-carousel-heading.ts",
  "logos-partner-network": "src/logos-partner-network.ts",
  "logos-two-row-grid": "src/logos-two-row-grid.ts",
  "logos-marquee-muted": "src/logos-marquee-muted.ts",
  "logos-centered-simple": "src/logos-centered-simple.ts",
  "logos-numbered-carousel": "src/logos-numbered-carousel.ts",
  "logos-double-carousel-pattern": "src/logos-double-carousel-pattern.ts",
  "logos-minimal-carousel": "src/logos-minimal-carousel.ts",
  "logos-partner-grid-sidebar": "src/logos-partner-grid-sidebar.ts",
  "process-sticky-steps": "src/process-sticky-steps.ts",
  "process-scroll-image": "src/process-scroll-image.ts",
  "process-hover-cards": "src/process-hover-cards.ts",
  "process-icon-timeline": "src/process-icon-timeline.ts",
  "process-expandable-timeline": "src/process-expandable-timeline.ts",
  "process-roadmap-timeline": "src/process-roadmap-timeline.ts",
  "process-mission-principles": "src/process-mission-principles.ts",
  "process-steps-grid": "src/process-steps-grid.ts",
  "process-numbered-services": "src/process-numbered-services.ts",
  "project-alternating-motion": "src/project-alternating-motion.ts",
  "project-background-reveal": "src/project-background-reveal.ts",
  "project-card-overlay": "src/project-card-overlay.ts",
  "project-carousel-cinematic": "src/project-carousel-cinematic.ts",
  "project-carousel-detail-cards": "src/project-carousel-detail-cards.ts",
  "project-carousel-minimal": "src/project-carousel-minimal.ts",
  "project-experience-quote": "src/project-experience-quote.ts",
  "project-featured-carousel": "src/project-featured-carousel.ts",
  "project-filterable-gallery": "src/project-filterable-gallery.ts",
  "project-filterable-three-column": "src/project-filterable-three-column.ts",
  "project-grid-gallery": "src/project-grid-gallery.ts",
  "project-grid-motion": "src/project-grid-motion.ts",
  "project-horizontal-cards": "src/project-horizontal-cards.ts",
  "project-hover-reveal-grid": "src/project-hover-reveal-grid.ts",
  "project-interactive-hover-reveal": "src/project-interactive-hover-reveal.ts",
  "project-masonry-columns": "src/project-masonry-columns.ts",
  "project-nature-mosaic": "src/project-nature-mosaic.ts",
  "project-scroll-reveal": "src/project-scroll-reveal.ts",
  "project-showcase-alternating": "src/project-showcase-alternating.ts",
  "project-sticky-scroll": "src/project-sticky-scroll.ts",
  "project-studio-hover-preview": "src/project-studio-hover-preview.ts",
  "project-table-list": "src/project-table-list.ts",
  "project-video-carousel": "src/project-video-carousel.ts",
  "project-video-hover-bento": "src/project-video-hover-bento.ts",
  "project-video-hover-grid": "src/project-video-hover-grid.ts",
  "project-video-hover-rounded": "src/project-video-hover-rounded.ts",
  "project-video-hover-stack": "src/project-video-hover-stack.ts",
  "project-video-hover-two-by-two": "src/project-video-hover-two-by-two.ts",
  "project-work-showcase": "src/project-work-showcase.ts",
  "project-zigzag-layout": "src/project-zigzag-layout.ts",
  "project-detail-architecture-carousel":
    "src/project-detail-architecture-carousel.ts",
  "project-detail-card-header": "src/project-detail-card-header.ts",
  "project-detail-case-study-prose": "src/project-detail-case-study-prose.ts",
  "project-detail-compact-metadata": "src/project-detail-compact-metadata.ts",
  "project-detail-exhibition-sidebar":
    "src/project-detail-exhibition-sidebar.ts",
  "project-detail-fashion-editorial": "src/project-detail-fashion-editorial.ts",
  "project-detail-fullscreen-hero": "src/project-detail-fullscreen-hero.ts",
  "project-detail-grid-gallery": "src/project-detail-grid-gallery.ts",
  "project-detail-hero-metadata": "src/project-detail-hero-metadata.ts",
  "project-detail-hover-gallery": "src/project-detail-hover-gallery.ts",
  "project-detail-large-hero-featured":
    "src/project-detail-large-hero-featured.ts",
  "project-detail-list-related": "src/project-detail-list-related.ts",
  "project-detail-mask-reveal": "src/project-detail-mask-reveal.ts",
  "project-detail-minimal-centered": "src/project-detail-minimal-centered.ts",
  "project-detail-numbered-sections": "src/project-detail-numbered-sections.ts",
  "project-detail-parallax-scroll": "src/project-detail-parallax-scroll.ts",
  "project-detail-photography-breadcrumb":
    "src/project-detail-photography-breadcrumb.ts",
  "project-detail-sculpture-showcase":
    "src/project-detail-sculpture-showcase.ts",
  "project-detail-sidebar-navigation":
    "src/project-detail-sidebar-navigation.ts",
  "project-detail-sidebar-sticky": "src/project-detail-sidebar-sticky.ts",
  "project-detail-split-materials": "src/project-detail-split-materials.ts",
  "project-detail-tabbed-case-study": "src/project-detail-tabbed-case-study.ts",
  "banner-promo-cta": "src/banner-promo-cta.ts",
  "banner-countdown-sale": "src/banner-countdown-sale.ts",
  "banner-delivery-countdown": "src/banner-delivery-countdown.ts",
  "banner-announcement-dismissible": "src/banner-announcement-dismissible.ts",
  "banner-privacy-notice": "src/banner-privacy-notice.ts",
  "banner-survey-incentive": "src/banner-survey-incentive.ts",
  "banner-social-follow": "src/banner-social-follow.ts",
  "banner-gdpr-rights": "src/banner-gdpr-rights.ts",
  "banner-event-promo": "src/banner-event-promo.ts",
  "banner-floating-offer": "src/banner-floating-offer.ts",
  "industries-hover-reveal-grid": "src/industries-hover-reveal-grid.ts",
  "industries-badge-list-bordered": "src/industries-badge-list-bordered.ts",
  "industries-timeline-table": "src/industries-timeline-table.ts",
  "industries-expandable-showcase": "src/industries-expandable-showcase.ts",
  "testimonials-list-verified": "src/testimonials-list-verified.ts",
  "testimonials-images-helpful": "src/testimonials-images-helpful.ts",
  "testimonials-bento-grid": "src/testimonials-bento-grid.ts",
  "testimonials-twitter-cards": "src/testimonials-twitter-cards.ts",
  "testimonials-carousel-image": "src/testimonials-carousel-image.ts",
  "testimonials-centered-avatars": "src/testimonials-centered-avatars.ts",
  "testimonials-company-logo": "src/testimonials-company-logo.ts",
  "testimonials-grid-add-review": "src/testimonials-grid-add-review.ts",
  "testimonials-marquee": "src/testimonials-marquee.ts",
  "testimonials-simple-grid": "src/testimonials-simple-grid.ts",
  "testimonials-slider-minimal": "src/testimonials-slider-minimal.ts",
  "testimonials-split-image": "src/testimonials-split-image.ts",
  "testimonials-stats-header": "src/testimonials-stats-header.ts",
  "testimonials-wall-compact": "src/testimonials-wall-compact.ts",
  "testimonials-mini-dividers": "src/testimonials-mini-dividers.ts",
  "testimonials-logo-cards": "src/testimonials-logo-cards.ts",
  "testimonials-quote-carousel": "src/testimonials-quote-carousel.ts",
  "testimonials-animated-split": "src/testimonials-animated-split.ts",
  "testimonials-scrolling-columns": "src/testimonials-scrolling-columns.ts",
  "testimonials-minimal-numbered": "src/testimonials-minimal-numbered.ts",
  "testimonials-parallax-number": "src/testimonials-parallax-number.ts",
  "testimonials-masonry-grid": "src/testimonials-masonry-grid.ts",
  "testimonials-large-quote": "src/testimonials-large-quote.ts",
  "service-detail-prose-minimal": "src/service-detail-prose-minimal.ts",
  "service-detail-image-hero": "src/service-detail-image-hero.ts",
  "service-detail-stats-hero": "src/service-detail-stats-hero.ts",
  "service-detail-sidebar-stats": "src/service-detail-sidebar-stats.ts",
  "service-detail-sidebar-related": "src/service-detail-sidebar-related.ts",
  "service-detail-centered-expertise":
    "src/service-detail-centered-expertise.ts",
  "service-detail-compact-cards": "src/service-detail-compact-cards.ts",
  "resource-list-hero-filter": "src/resource-list-hero-filter.ts",
  "resource-list-featured-grid": "src/resource-list-featured-grid.ts",
  "resource-list-featured-articles": "src/resource-list-featured-articles.ts",
  "resource-list-news-updates": "src/resource-list-news-updates.ts",
  "resource-list-course-cards": "src/resource-list-course-cards.ts",
  "resource-detail-whitepaper-sidebar":
    "src/resource-detail-whitepaper-sidebar.ts",
  "resource-detail-article-hero": "src/resource-detail-article-hero.ts",
  "resource-detail-document-sidebar": "src/resource-detail-document-sidebar.ts",
  "stats-simple-grid": "src/stats-simple-grid.ts",
  "stats-icon-cards": "src/stats-icon-cards.ts",
  "stats-timeline-tabs": "src/stats-timeline-tabs.ts",
  "stats-primary-secondary": "src/stats-primary-secondary.ts",
  "stats-growth-timeline": "src/stats-growth-timeline.ts",
  "stats-impact-grid": "src/stats-impact-grid.ts",
  "stats-circular-progress": "src/stats-circular-progress.ts",
  "stats-card-group": "src/stats-card-group.ts",
  "stats-animated-counter": "src/stats-animated-counter.ts",
  "stats-number-ticker": "src/stats-number-ticker.ts",
  "stats-milestone-sidebar": "src/stats-milestone-sidebar.ts",
  "stats-bar-comparison": "src/stats-bar-comparison.ts",
  "link-tree-block": "src/link-tree-block.ts",
  "link-page-minimal-profile": "src/link-page-minimal-profile.ts",
  "link-page-newsletter-social": "src/link-page-newsletter-social.ts",
  "link-page-grid-cards": "src/link-page-grid-cards.ts",
  "link-page-bento-layout": "src/link-page-bento-layout.ts",
  "timeline-vertical-icon-dashed": "src/timeline-vertical-icon-dashed.ts",
  "timeline-scroll-sticky-image": "src/timeline-scroll-sticky-image.ts",
  "timeline-two-column-featured": "src/timeline-two-column-featured.ts",
  "timeline-alternating-diagonal": "src/timeline-alternating-diagonal.ts",
  "timeline-ai-workflow-cards": "src/timeline-ai-workflow-cards.ts",
  "timeline-productivity-list": "src/timeline-productivity-list.ts",
  "timeline-stepper-animated": "src/timeline-stepper-animated.ts",
  "timeline-changelog-badges": "src/timeline-changelog-badges.ts",
  "timeline-history-prose": "src/timeline-history-prose.ts",
  "timeline-horizontal-phases": "src/timeline-horizontal-phases.ts",
  "timeline-horizontal-icons": "src/timeline-horizontal-icons.ts",
  "timeline-tabbed-phases": "src/timeline-tabbed-phases.ts",
  "timeline-product-launch": "src/timeline-product-launch.ts",
  "timeline-scroll-highlight": "src/timeline-scroll-highlight.ts",
  "about-location-info-hero": "src/about-location-info-hero.ts",
  "about-network-spotlight": "src/about-network-spotlight.ts",
  "about-story-expertise": "src/about-story-expertise.ts",
  "about-split-hero": "src/about-split-hero.ts",
  "community-initiatives": "src/community-initiatives.ts",
  "contact-callback": "src/contact-callback.ts",
  "contact-card": "src/contact-card.ts",
  "contact-careers": "src/contact-careers.ts",
  "contact-catering": "src/contact-catering.ts",
  "contact-consultation": "src/contact-consultation.ts",
  "contact-dark": "src/contact-dark.ts",
  "contact-demo": "src/contact-demo.ts",
  "contact-emergency": "src/contact-emergency.ts",
  "contact-event": "src/contact-event.ts",
  "contact-faq": "src/contact-faq.ts",
  "contact-feedback": "src/contact-feedback.ts",
  "contact-fitness": "src/contact-fitness.ts",
  "contact-floating-banner": "src/contact-floating-banner.ts",
  "contact-guest": "src/contact-guest.ts",
  "contact-help-center": "src/contact-help-center.ts",
  "contact-image": "src/contact-image.ts",
  "contact-insurance": "src/contact-insurance.ts",
  "contact-interview": "src/contact-interview.ts",
  "contact-locations": "src/contact-locations.ts",
  "contact-maintenance": "src/contact-maintenance.ts",
  "contact-map": "src/contact-map.ts",
  "contact-minimal": "src/contact-minimal.ts",
  "contact-moving": "src/contact-moving.ts",
  "contact-multistep": "src/contact-multistep.ts",
  "contact-partnership": "src/contact-partnership.ts",
  "contact-photography": "src/contact-photography.ts",
  "contact-press": "src/contact-press.ts",
  "contact-quote": "src/contact-quote.ts",
  "contact-referral": "src/contact-referral.ts",
  "contact-report": "src/contact-report.ts",
  "contact-reservation": "src/contact-reservation.ts",
  "contact-retreat": "src/contact-retreat.ts",
  "contact-rsvp": "src/contact-rsvp.ts",
  "contact-sales": "src/contact-sales.ts",
  "contact-schedule": "src/contact-schedule.ts",
  "contact-sponsorship": "src/contact-sponsorship.ts",
  "contact-support": "src/contact-support.ts",
  "contact-tenant": "src/contact-tenant.ts",
  "contact-vendor": "src/contact-vendor.ts",
  "contact-volunteer": "src/contact-volunteer.ts",
  "contact-warranty": "src/contact-warranty.ts",
  "contact-wedding": "src/contact-wedding.ts",
  "cta-image-overlay-centered": "src/cta-image-overlay-centered.ts",
  "feature-capabilities-grid": "src/feature-capabilities-grid.ts",
  "footer-brand-links-contact": "src/footer-brand-links-contact.ts",
  "footer-comprehensive-links": "src/footer-comprehensive-links.ts",
  "hero-floating-images": "src/hero-floating-images.ts",
  "hero-overlay-cta-grid": "src/hero-overlay-cta-grid.ts",
  "hero-split-icon-cards": "src/hero-split-icon-cards.ts",
  "list-achievements-showcase": "src/list-achievements-showcase.ts",
  "list-career-timeline": "src/list-career-timeline.ts",
  "list-feature-comparison": "src/list-feature-comparison.ts",
  "list-metrics-dashboard": "src/list-metrics-dashboard.ts",
  "list-searchable-grid": "src/list-searchable-grid.ts",
  "list-service-category-table": "src/list-service-category-table.ts",
  "offer-modal-membership-image": "src/offer-modal-membership-image.ts",
  "offer-modal-newsletter-discount": "src/offer-modal-newsletter-discount.ts",
  "offer-modal-sheet-newsletter": "src/offer-modal-sheet-newsletter.ts",
  "pricing-addons-cards": "src/pricing-addons-cards.ts",
  "pricing-addons-featured": "src/pricing-addons-featured.ts",
  "pricing-collapsible-plans": "src/pricing-collapsible-plans.ts",
  "pricing-columns-toggle": "src/pricing-columns-toggle.ts",
  "pricing-comparison-headers": "src/pricing-comparison-headers.ts",
  "pricing-comparison-table": "src/pricing-comparison-table.ts",
  "pricing-discount-card": "src/pricing-discount-card.ts",
  "pricing-enterprise-contact": "src/pricing-enterprise-contact.ts",
  "pricing-feature-matrix": "src/pricing-feature-matrix.ts",
  "pricing-four-tier-toggle": "src/pricing-four-tier-toggle.ts",
  "pricing-full-comparison": "src/pricing-full-comparison.ts",
  "pricing-gradient-cards": "src/pricing-gradient-cards.ts",
  "pricing-icon-headers": "src/pricing-icon-headers.ts",
  "pricing-minimal-cards": "src/pricing-minimal-cards.ts",
  "pricing-packages-radio": "src/pricing-packages-radio.ts",
  "pricing-popular-highlight": "src/pricing-popular-highlight.ts",
  "pricing-radio-toggle": "src/pricing-radio-toggle.ts",
  "pricing-responsive-table": "src/pricing-responsive-table.ts",
  "pricing-services-cards": "src/pricing-services-cards.ts",
  "pricing-simple-card": "src/pricing-simple-card.ts",
  "pricing-single-card": "src/pricing-single-card.ts",
  "pricing-split-layout": "src/pricing-split-layout.ts",
  "pricing-spotlight-card": "src/pricing-spotlight-card.ts",
  "pricing-switch-cards": "src/pricing-switch-cards.ts",
  "pricing-tabs-toggle": "src/pricing-tabs-toggle.ts",
  "pricing-tier-grid": "src/pricing-tier-grid.ts",
  "pricing-toggle-cards": "src/pricing-toggle-cards.ts",
  "pricing-toggle-period": "src/pricing-toggle-period.ts",
  "pricing-two-column-basic": "src/pricing-two-column-basic.ts",
  "services-list-feature-spotlight": "src/services-list-feature-spotlight.ts",
  "services-list-accordion": "src/services-list-accordion.ts",
  "services-list-accordion-benefits": "src/services-list-accordion-benefits.ts",
  "services-list-cards-hover": "src/services-list-cards-hover.ts",
  "services-list-category-accordion": "src/services-list-category-accordion.ts",
  "services-list-centered-icons": "src/services-list-centered-icons.ts",
  "services-list-culture-tabs": "src/services-list-culture-tabs.ts",
  "services-list-expandable-cards": "src/services-list-expandable-cards.ts",
  "services-list-featured-highlight": "src/services-list-featured-highlight.ts",
  "services-list-hero-cards": "src/services-list-hero-cards.ts",
  "services-list-icon-grid": "src/services-list-icon-grid.ts",
  "services-list-image-cards": "src/services-list-image-cards.ts",
  "services-list-image-overlay-grid": "src/services-list-image-overlay-grid.ts",
  "services-list-masonry": "src/services-list-masonry.ts",
  "services-list-methodology-steps": "src/services-list-methodology-steps.ts",
  "services-list-minimal-grid": "src/services-list-minimal-grid.ts",
  "services-list-muted-cards": "src/services-list-muted-cards.ts",
  "services-list-numbered-steps": "src/services-list-numbered-steps.ts",
  "services-list-pricing-grid": "src/services-list-pricing-grid.ts",
  "services-list-progress-sidebar": "src/services-list-progress-sidebar.ts",
  "services-list-split-checklist": "src/services-list-split-checklist.ts",
  "services-list-sticky-image": "src/services-list-sticky-image.ts",
  "services-list-table-hover": "src/services-list-table-hover.ts",
  "services-list-tabs-features": "src/services-list-tabs-features.ts",
  "services-list-timeline": "src/services-list-timeline.ts",
  "services-list-two-column-grid": "src/services-list-two-column-grid.ts",
  "services-list-vertical-tags": "src/services-list-vertical-tags.ts",
  "services-list-video-showcase": "src/services-list-video-showcase.ts",
  registry: "src/registry.ts",
  utils: "lib/utils.ts",
  types: "src/types/index.ts",
};

export default defineConfig({
  ...sharedConfig,
  entry: allEntries,
  clean: true,
  // Add "use client" directive to client components after build
  onSuccess: async () => {
    const distDir = "dist";

    for (const entryName of clientEntryNames) {
      // Process both ESM and CJS outputs
      const files = [
        join(distDir, `${entryName}.js`),
        join(distDir, `${entryName}.cjs`),
      ];

      for (const filePath of files) {
        try {
          const content = readFileSync(filePath, "utf-8");
          // Only add if not already present
          if (!content.startsWith('"use client"')) {
            writeFileSync(filePath, `"use client";\n${content}`);
          }
        } catch {
          // File might not exist, skip
        }
      }
    }

    console.log("✓ Added 'use client' directive to client components");
  },
});
