import { defineConfig, type Options } from "tsup";
import { writeFileSync, readFileSync } from "fs";
import { join } from "path";

// Entry points that contain client-side React hooks and need "use client" directive
const clientEntryNames = new Set([
  "animated-dialog",
  "page-hero-banner",
  "dynamic-icon",
  "pressable",
  "hooks",
  "use-navigation",
  "media-hover-ctas",
  "feature-showcase",
  "team-media-showcase",
  "footer-links-grid",
  "footer-social-newsletter",
  "footer-social-apps",
  "footer-simple-centered",
  "footer-brand-description",
  "footer-newsletter-grid",
  "footer-cta-banner",
  "footer-contact-card",
  "footer-background-card",
  "footer-animated-social",
  "footer-newsletter-minimal",
  "footer-cta-social",
  "footer-nav-social",
  "expandable-case-study-cards",
  "carousel-badge-cards",
  "carousel-gradient-overlay",
  "carousel-demo-link",
  "auto-scroll-carousel",
  "carousel-sidebar-resources",
  "carousel-icon-tabs",
  "testimonial-carousel-cards",
  "carousel-icon-sidebar",
  "carousel-gradient-text",
  "service-hover-carousel",
  "carousel-tabs-content",
  "carousel-scale-focus",
  "masonry-motion-grid",
  "blur-vignette-grid",
  "interior-carousel",
  "about-mission-features",
  "about-stats-showcase",
  "about-company-profile",
  "about-vision-gallery",
  "about-developer-story",
  "about-story-gallery",
  "about-streamline-team",
  "about-developer-profile",
  "about-startup-team",
  "about-minimal-story",
  "about-story-hero",
  "about-stats-sidebar",
  "about-interactive-tabs",
  "about-mission-dual-image",
  "radial-gradient-top",
  "radial-gradient-bottom",
  "grid-basic",
  "grid-fade-top-left",
  "grid-fade-top-right",
  "grid-fade-top",
  "grid-fade-bottom",
  "grid-fade-bottom-left",
  "grid-fade-bottom-right",
  "grid-fade-center",
  "diagonal-cross-basic",
  "diagonal-cross-fade-top-left",
  "diagonal-cross-fade-top-right",
  "diagonal-cross-fade-top",
  "diagonal-cross-fade-bottom",
  "diagonal-cross-fade-bottom-left",
  "diagonal-cross-fade-bottom-right",
  "diagonal-cross-fade-center",
  "dashed-grid-basic",
  "dashed-grid-fade-top-left",
  "dashed-grid-fade-top-right",
  "dashed-grid-fade-top",
  "dashed-grid-fade-bottom",
  "dashed-grid-fade-bottom-left",
  "dashed-grid-fade-bottom-right",
  "dashed-grid-fade-center",
  "gradient-glow-top",
  "gradient-glow-bottom",
  "spotlight-left",
  "spotlight-right",
  "circuit-board-basic",
  "circuit-board-fade-top-left",
  "circuit-board-fade-top-right",
  "circuit-board-fade-top",
  "circuit-board-fade-bottom",
  "circuit-board-fade-bottom-left",
  "circuit-board-fade-bottom-right",
  "circuit-board-fade-center",
  "grid-dots-basic",
  "grid-dots-fade-center",
  "components",
  "index",
]);

// Shared configuration
const sharedConfig: Partial<Options> = {
  format: ["esm", "cjs"],
  dts: true,
  splitting: false,
  sourcemap: true,
  treeshake: true,
  minify: false,
  external: [
    "react",
    "react-dom",
    "framer-motion",
    "@opensite/hooks",
    "@legendapp/state",
    "valibot",
  ],
};

// All entries
const allEntries = {
  index: "src/index.ts",
  components: "src/components.ts",
  container: "components/ui/container.tsx",
  section: "components/ui/section.tsx",
  "animated-dialog": "components/ui/animated-dialog.tsx",
  "page-hero-banner": "components/ui/page-hero-banner.tsx",
  button: "components/ui/button.tsx",
  card: "components/ui/card.tsx",
  badge: "components/ui/badge.tsx",
  popover: "components/ui/popover.tsx",
  "dynamic-icon": "components/ui/dynamic-icon.tsx",
  pressable: "lib/Pressable.tsx",
  hooks: "lib/hooks.ts",
  "use-navigation": "lib/useNavigation.ts",
  "alternating-blocks": "src/alternating-blocks.ts",
  "media-hover-ctas": "src/media-hover-ctas.ts",
  "feature-showcase": "src/feature-showcase.ts",
  "team-media-showcase": "src/team-media-showcase.ts",
  "footer-links-grid": "src/footer-links-grid.ts",
  "footer-social-newsletter": "src/footer-social-newsletter.ts",
  "footer-social-apps": "src/footer-social-apps.ts",
  "footer-simple-centered": "src/footer-simple-centered.ts",
  "footer-brand-description": "src/footer-brand-description.ts",
  "footer-newsletter-grid": "src/footer-newsletter-grid.ts",
  "footer-cta-banner": "src/footer-cta-banner.ts",
  "footer-contact-card": "src/footer-contact-card.ts",
  "footer-background-card": "src/footer-background-card.ts",
  "footer-animated-social": "src/footer-animated-social.ts",
  "footer-newsletter-minimal": "src/footer-newsletter-minimal.ts",
  "footer-cta-social": "src/footer-cta-social.ts",
    "footer-nav-social": "src/footer-nav-social.ts",
    "expandable-case-study-cards": "src/expandable-case-study-cards.ts",
    "carousel-badge-cards": "src/carousel-badge-cards.ts",
    "carousel-gradient-overlay": "src/carousel-gradient-overlay.ts",
    "carousel-demo-link": "src/carousel-demo-link.ts",
    "auto-scroll-carousel": "src/auto-scroll-carousel.ts",
    "carousel-sidebar-resources": "src/carousel-sidebar-resources.ts",
    "carousel-icon-tabs": "src/carousel-icon-tabs.ts",
    "testimonial-carousel-cards": "src/testimonial-carousel-cards.ts",
    "carousel-icon-sidebar": "src/carousel-icon-sidebar.ts",
    "carousel-gradient-text": "src/carousel-gradient-text.ts",
    "service-hover-carousel": "src/service-hover-carousel.ts",
    "carousel-tabs-content": "src/carousel-tabs-content.ts",
    "carousel-scale-focus": "src/carousel-scale-focus.ts",
    "masonry-motion-grid": "src/masonry-motion-grid.ts",
    "blur-vignette-grid": "src/blur-vignette-grid.ts",
    "interior-carousel": "src/interior-carousel.ts",
    "about-mission-features": "src/about-mission-features.ts",
    "about-stats-showcase": "src/about-stats-showcase.ts",
    "about-company-profile": "src/about-company-profile.ts",
    "about-vision-gallery": "src/about-vision-gallery.ts",
    "about-developer-story": "src/about-developer-story.ts",
    "about-story-gallery": "src/about-story-gallery.ts",
    "about-streamline-team": "src/about-streamline-team.ts",
    "about-developer-profile": "src/about-developer-profile.ts",
    "about-startup-team": "src/about-startup-team.ts",
    "about-minimal-story": "src/about-minimal-story.ts",
    "about-story-hero": "src/about-story-hero.ts",
    "about-stats-sidebar": "src/about-stats-sidebar.ts",
    "about-interactive-tabs": "src/about-interactive-tabs.ts",
    "about-mission-dual-image": "src/about-mission-dual-image.ts",
    "radial-gradient-top": "src/radial-gradient-top.ts",
    "radial-gradient-bottom": "src/radial-gradient-bottom.ts",
    "grid-basic": "src/grid-basic.ts",
    "grid-fade-top-left": "src/grid-fade-top-left.ts",
    "grid-fade-top-right": "src/grid-fade-top-right.ts",
    "grid-fade-top": "src/grid-fade-top.ts",
    "grid-fade-bottom": "src/grid-fade-bottom.ts",
    "grid-fade-bottom-left": "src/grid-fade-bottom-left.ts",
    "grid-fade-bottom-right": "src/grid-fade-bottom-right.ts",
    "grid-fade-center": "src/grid-fade-center.ts",
    "diagonal-cross-basic": "src/diagonal-cross-basic.ts",
    "diagonal-cross-fade-top-left": "src/diagonal-cross-fade-top-left.ts",
    "diagonal-cross-fade-top-right": "src/diagonal-cross-fade-top-right.ts",
    "diagonal-cross-fade-top": "src/diagonal-cross-fade-top.ts",
    "diagonal-cross-fade-bottom": "src/diagonal-cross-fade-bottom.ts",
    "diagonal-cross-fade-bottom-left": "src/diagonal-cross-fade-bottom-left.ts",
    "diagonal-cross-fade-bottom-right": "src/diagonal-cross-fade-bottom-right.ts",
    "diagonal-cross-fade-center": "src/diagonal-cross-fade-center.ts",
    "dashed-grid-basic": "src/dashed-grid-basic.ts",
    "dashed-grid-fade-top-left": "src/dashed-grid-fade-top-left.ts",
    "dashed-grid-fade-top-right": "src/dashed-grid-fade-top-right.ts",
    "dashed-grid-fade-top": "src/dashed-grid-fade-top.ts",
    "dashed-grid-fade-bottom": "src/dashed-grid-fade-bottom.ts",
    "dashed-grid-fade-bottom-left": "src/dashed-grid-fade-bottom-left.ts",
    "dashed-grid-fade-bottom-right": "src/dashed-grid-fade-bottom-right.ts",
    "dashed-grid-fade-center": "src/dashed-grid-fade-center.ts",
    "gradient-glow-top": "src/gradient-glow-top.ts",
    "gradient-glow-bottom": "src/gradient-glow-bottom.ts",
    "spotlight-left": "src/spotlight-left.ts",
    "spotlight-right": "src/spotlight-right.ts",
    "circuit-board-basic": "src/circuit-board-basic.ts",
    "circuit-board-fade-top-left": "src/circuit-board-fade-top-left.ts",
    "circuit-board-fade-top-right": "src/circuit-board-fade-top-right.ts",
    "circuit-board-fade-top": "src/circuit-board-fade-top.ts",
    "circuit-board-fade-bottom": "src/circuit-board-fade-bottom.ts",
    "circuit-board-fade-bottom-left": "src/circuit-board-fade-bottom-left.ts",
    "circuit-board-fade-bottom-right": "src/circuit-board-fade-bottom-right.ts",
    "circuit-board-fade-center": "src/circuit-board-fade-center.ts",
    "grid-dots-basic": "src/grid-dots-basic.ts",
    "grid-dots-fade-center": "src/grid-dots-fade-center.ts",
    registry: "src/registry.ts",
  utils: "lib/utils.ts",
  types: "src/types/index.ts",
};

export default defineConfig({
  ...sharedConfig,
  entry: allEntries,
  clean: true,
  // Add "use client" directive to client components after build
  onSuccess: async () => {
    const distDir = "dist";

    for (const entryName of clientEntryNames) {
      // Process both ESM and CJS outputs
      const files = [
        join(distDir, `${entryName}.js`),
        join(distDir, `${entryName}.cjs`),
      ];

      for (const filePath of files) {
        try {
          const content = readFileSync(filePath, "utf-8");
          // Only add if not already present
          if (!content.startsWith('"use client"')) {
            writeFileSync(filePath, `"use client";\n${content}`);
          }
        } catch {
          // File might not exist, skip
        }
      }
    }

    console.log("✓ Added 'use client' directive to client components");
  },
});
