import { defineConfig, type Options } from "tsup";
import { writeFileSync, readFileSync } from "fs";
import { join } from "path";

// Entry points that contain client-side React hooks and need "use client" directive
const clientEntryNames = new Set([
  "animated-dialog",
  "page-hero-banner",
  "dynamic-icon",
  "pressable",
  "hooks",
  "use-navigation",
  "media-hover-ctas",
  "feature-showcase",
  "team-media-showcase",
  "footer-links-grid",
  "footer-social-newsletter",
  "footer-social-apps",
  "footer-simple-centered",
  "footer-brand-description",
  "footer-newsletter-grid",
  "footer-cta-banner",
  "footer-contact-card",
  "footer-background-card",
  "footer-animated-social",
  "footer-newsletter-minimal",
  "footer-cta-social",
  "footer-nav-social",
  "expandable-case-study-cards",
  "carousel-badge-cards",
  "carousel-gradient-overlay",
  "carousel-demo-link",
  "auto-scroll-carousel",
  "carousel-sidebar-resources",
  "carousel-icon-tabs",
  "testimonial-carousel-cards",
  "carousel-icon-sidebar",
  "carousel-gradient-text",
  "service-hover-carousel",
  "carousel-tabs-content",
  "carousel-scale-focus",
  "masonry-motion-grid",
  "blur-vignette-grid",
  "interior-carousel",
  "about-mission-features",
  "about-stats-showcase",
  "about-company-profile",
  "about-vision-gallery",
  "about-developer-story",
  "about-story-gallery",
  "about-streamline-team",
  "about-developer-profile",
  "about-startup-team",
  "about-minimal-story",
  "about-story-hero",
  "about-stats-sidebar",
  "about-interactive-tabs",
  "about-mission-dual-image",
  "radial-gradient-top",
  "radial-gradient-bottom",
  "grid-basic",
  "grid-fade-top-left",
  "grid-fade-top-right",
  "grid-fade-top",
  "grid-fade-bottom",
  "grid-fade-bottom-left",
  "grid-fade-bottom-right",
  "grid-fade-center",
  "diagonal-cross-basic",
  "diagonal-cross-fade-top-left",
  "diagonal-cross-fade-top-right",
  "diagonal-cross-fade-top",
  "diagonal-cross-fade-bottom",
  "diagonal-cross-fade-bottom-left",
  "diagonal-cross-fade-bottom-right",
  "diagonal-cross-fade-center",
  "dashed-grid-basic",
  "dashed-grid-fade-top-left",
  "dashed-grid-fade-top-right",
  "dashed-grid-fade-top",
  "dashed-grid-fade-bottom",
  "dashed-grid-fade-bottom-left",
  "dashed-grid-fade-bottom-right",
  "dashed-grid-fade-center",
  "gradient-glow-top",
  "gradient-glow-bottom",
  "spotlight-left",
  "spotlight-right",
  "circuit-board-basic",
  "circuit-board-fade-top-left",
  "circuit-board-fade-top-right",
  "circuit-board-fade-top",
  "circuit-board-fade-bottom",
  "circuit-board-fade-bottom-left",
  "circuit-board-fade-bottom-right",
  "circuit-board-fade-center",
  "grid-dots-basic",
  "grid-dots-fade-center",
  "blog-grid-author-cards",
  "blog-cards-tagline-cta",
  "blog-cards-read-time",
  "blog-category-overlay",
  "blog-featured-popular",
  "blog-related-articles",
  "blog-tech-insights",
  "blog-horizontal-cards",
  "blog-filtered-results",
  "blog-masonry-featured",
  "blog-horizontal-timeline",
  "blog-grid-nine-posts",
  "article-hero-prose",
  "article-sidebar-sticky",
  "article-toc-sidebar",
  "article-breadcrumb-social",
  "article-compact-toc",
  "article-chapters-author",
  "article-split-animated",
  "faq-simple-accordion",
  "faq-static-list",
  "faq-centered-accordion",
  "faq-badge-support",
  "faq-numbered-list",
  "faq-numbered-grid",
  "faq-split-help",
  "faq-categorized-sections",
  "faq-muted-cards",
  "faq-bordered-badge",
  "faq-gradient-categories",
  "faq-sidebar-navigation",
  "faq-card-categories",
  "faq-icon-benefits",
  "faq-rounded-cards",
  "faq-profile-sidebar",
  "hero-badge-image-split",
  "hero-image-left-content",
  "hero-centered-image-grid",
  "hero-centered-screenshot",
  "hero-pattern-badge-logos",
  "hero-logo-centered-screenshot",
  "hero-pattern-logo-tech-stack",
  "hero-announcement-badge",
  "hero-tech-carousel",
  "hero-simple-centered-image",
  "hero-platform-features-grid",
  "hero-spiral-pattern-cards",
  "hero-split-spiral-shapes",
  "hero-split-geometric-shapes",
  "hero-community-survey-cta",
  "hero-marketplace-scattered-images",
  "hero-badge-shadow-overlay",
  "hero-video-background-dark",
  "hero-grid-pattern-efficiency",
  "hero-dashed-border-features",
  "hero-design-carousel-portfolio",
  "hero-gradient-client-focused",
  "hero-premium-split-avatars",
  "hero-ui-library-showcase",
  "hero-fullscreen-background-image",
  "hero-fullscreen-logo-cta",
  "hero-gradient-avatars-rating",
  "hero-task-timer-animated",
  "hero-ai-powered-carousel",
  "hero-ad-campaign-expert",
  "hero-adaptable-product-grid",
  "hero-presentation-platform-video",
  "hero-grid-pattern-solutions",
  "hero-crm-streamlined",
  "hero-billing-platform-logos",
  "hero-software-growth-video-dialog",
  "hero-conversion-video-play",
  "hero-design-showcase-logos",
  "hero-video-overlay-stars",
  "hero-productivity-launcher-video",
  "hero-hiring-animated-text",
  "hero-split-image-newsletter",
  "hero-centered-gradient-cta",
  "hero-stats-social-proof",
  "hero-feature-cards-grid",
  "hero-testimonial-image-grid",
  "hero-design-system-3d",
  "hero-architecture-fullscreen",
  "hero-innovation-image-grid",
  "hero-video-dialog-gradient",
  "hero-minimal-centered-dark",
  "hero-product-showcase-floating",
  "hero-saas-dashboard-preview",
  "hero-therapy-testimonial-grid",
  "hero-mental-health-team",
  "hero-mentorship-video-split",
  "hero-business-operations-mosaic",
  "hero-agency-animated-images",
  "hero-welcome-asymmetric-images",
  "hero-startup-launch-cta",
  "hero-enterprise-security",
  "hero-creative-studio-stacked",
  "hero-digital-agency-fullscreen",
  "hero-customer-support-layered",
  "hero-shared-inbox-layered",
  "hero-conversation-intelligence",
  "hero-business-carousel-dots",
  "hero-developer-tools-code",
  "hero-ecommerce-product-showcase",
  "hero-mobile-app-download",
  "hero-pricing-comparison",
  "hero-newsletter-minimal",
  "hero-coming-soon-countdown",
  "hero-event-registration",
  "hero-portfolio-creative",
    "case-studies-image-grid",
    "case-studies-testimonial-stats",
    "case-studies-featured-border",
    "case-studies-stats-card",
    "case-study-prose-sidebar",
    "case-study-toc-social-sidebar",
    "case-study-stats-metrics",
    "comparison-table-two-column",
    "comparison-feature-cards",
    "comparison-grid-badges",
    "comparison-metrics-rows",
    "comparison-image-cards",
    "comparison-table-tabs",
    "comparison-table-tooltips",
    "comparison-feature-grid",
    "comparison-ai-models",
    "comparison-legacy-modern",
    "navbar-dropdown-menu",
    "navbar-centered-menu",
    "navbar-mega-menu",
    "navbar-enterprise-mega",
    "navbar-feature-grid",
    "navbar-floating-pill",
    "navbar-platform-resources",
    "navbar-image-preview",
    "navbar-dark-icons",
    "navbar-animated-preview",
    "navbar-multi-column-groups",
    "navbar-sidebar-mobile",
    "navbar-transparent-overlay",
    "navbar-education-platform",
    "navbar-sticky-compact",
    "navbar-search-focused",
    "navbar-simple-links",
    "navbar-split-cta",
    "navbar-icon-links",
    "navbar-tabbed-sections",
    "navbar-fullscreen-menu",
    "logos-inline-tagline",
    "logos-certifications-grid",
    "logos-carousel-heading",
    "logos-partner-network",
    "logos-two-row-grid",
    "logos-marquee-muted",
    "logos-centered-simple",
    "logos-numbered-carousel",
    "logos-double-carousel-pattern",
    "logos-minimal-carousel",
    "logos-partner-grid-sidebar",
    "components",
  "index",
]);

// Shared configuration
const sharedConfig: Partial<Options> = {
  format: ["esm", "cjs"],
  dts: true,
  splitting: false,
  sourcemap: true,
  treeshake: true,
  minify: false,
  external: [
    "react",
    "react-dom",
    "framer-motion",
    "@opensite/hooks",
    "@legendapp/state",
    "valibot",
  ],
};

// All entries
const allEntries = {
  index: "src/index.ts",
  components: "src/components.ts",
  container: "components/ui/container.tsx",
  section: "components/ui/section.tsx",
  "animated-dialog": "components/ui/animated-dialog.tsx",
  "page-hero-banner": "components/ui/page-hero-banner.tsx",
  button: "components/ui/button.tsx",
  card: "components/ui/card.tsx",
  badge: "components/ui/badge.tsx",
  popover: "components/ui/popover.tsx",
  "dynamic-icon": "components/ui/dynamic-icon.tsx",
  pressable: "lib/Pressable.tsx",
  hooks: "lib/hooks.ts",
  "use-navigation": "lib/useNavigation.ts",
  "alternating-blocks": "src/alternating-blocks.ts",
  "media-hover-ctas": "src/media-hover-ctas.ts",
  "feature-showcase": "src/feature-showcase.ts",
  "team-media-showcase": "src/team-media-showcase.ts",
  "footer-links-grid": "src/footer-links-grid.ts",
  "footer-social-newsletter": "src/footer-social-newsletter.ts",
  "footer-social-apps": "src/footer-social-apps.ts",
  "footer-simple-centered": "src/footer-simple-centered.ts",
  "footer-brand-description": "src/footer-brand-description.ts",
  "footer-newsletter-grid": "src/footer-newsletter-grid.ts",
  "footer-cta-banner": "src/footer-cta-banner.ts",
  "footer-contact-card": "src/footer-contact-card.ts",
  "footer-background-card": "src/footer-background-card.ts",
  "footer-animated-social": "src/footer-animated-social.ts",
  "footer-newsletter-minimal": "src/footer-newsletter-minimal.ts",
  "footer-cta-social": "src/footer-cta-social.ts",
    "footer-nav-social": "src/footer-nav-social.ts",
    "expandable-case-study-cards": "src/expandable-case-study-cards.ts",
    "carousel-badge-cards": "src/carousel-badge-cards.ts",
    "carousel-gradient-overlay": "src/carousel-gradient-overlay.ts",
    "carousel-demo-link": "src/carousel-demo-link.ts",
    "auto-scroll-carousel": "src/auto-scroll-carousel.ts",
    "carousel-sidebar-resources": "src/carousel-sidebar-resources.ts",
    "carousel-icon-tabs": "src/carousel-icon-tabs.ts",
    "testimonial-carousel-cards": "src/testimonial-carousel-cards.ts",
    "carousel-icon-sidebar": "src/carousel-icon-sidebar.ts",
    "carousel-gradient-text": "src/carousel-gradient-text.ts",
    "service-hover-carousel": "src/service-hover-carousel.ts",
    "carousel-tabs-content": "src/carousel-tabs-content.ts",
    "carousel-scale-focus": "src/carousel-scale-focus.ts",
    "masonry-motion-grid": "src/masonry-motion-grid.ts",
    "blur-vignette-grid": "src/blur-vignette-grid.ts",
    "interior-carousel": "src/interior-carousel.ts",
    "about-mission-features": "src/about-mission-features.ts",
    "about-stats-showcase": "src/about-stats-showcase.ts",
    "about-company-profile": "src/about-company-profile.ts",
    "about-vision-gallery": "src/about-vision-gallery.ts",
    "about-developer-story": "src/about-developer-story.ts",
    "about-story-gallery": "src/about-story-gallery.ts",
    "about-streamline-team": "src/about-streamline-team.ts",
    "about-developer-profile": "src/about-developer-profile.ts",
    "about-startup-team": "src/about-startup-team.ts",
    "about-minimal-story": "src/about-minimal-story.ts",
    "about-story-hero": "src/about-story-hero.ts",
    "about-stats-sidebar": "src/about-stats-sidebar.ts",
    "about-interactive-tabs": "src/about-interactive-tabs.ts",
    "about-mission-dual-image": "src/about-mission-dual-image.ts",
    "radial-gradient-top": "src/radial-gradient-top.ts",
    "radial-gradient-bottom": "src/radial-gradient-bottom.ts",
    "grid-basic": "src/grid-basic.ts",
    "grid-fade-top-left": "src/grid-fade-top-left.ts",
    "grid-fade-top-right": "src/grid-fade-top-right.ts",
    "grid-fade-top": "src/grid-fade-top.ts",
    "grid-fade-bottom": "src/grid-fade-bottom.ts",
    "grid-fade-bottom-left": "src/grid-fade-bottom-left.ts",
    "grid-fade-bottom-right": "src/grid-fade-bottom-right.ts",
    "grid-fade-center": "src/grid-fade-center.ts",
    "diagonal-cross-basic": "src/diagonal-cross-basic.ts",
    "diagonal-cross-fade-top-left": "src/diagonal-cross-fade-top-left.ts",
    "diagonal-cross-fade-top-right": "src/diagonal-cross-fade-top-right.ts",
    "diagonal-cross-fade-top": "src/diagonal-cross-fade-top.ts",
    "diagonal-cross-fade-bottom": "src/diagonal-cross-fade-bottom.ts",
    "diagonal-cross-fade-bottom-left": "src/diagonal-cross-fade-bottom-left.ts",
    "diagonal-cross-fade-bottom-right": "src/diagonal-cross-fade-bottom-right.ts",
    "diagonal-cross-fade-center": "src/diagonal-cross-fade-center.ts",
    "dashed-grid-basic": "src/dashed-grid-basic.ts",
    "dashed-grid-fade-top-left": "src/dashed-grid-fade-top-left.ts",
    "dashed-grid-fade-top-right": "src/dashed-grid-fade-top-right.ts",
    "dashed-grid-fade-top": "src/dashed-grid-fade-top.ts",
    "dashed-grid-fade-bottom": "src/dashed-grid-fade-bottom.ts",
    "dashed-grid-fade-bottom-left": "src/dashed-grid-fade-bottom-left.ts",
    "dashed-grid-fade-bottom-right": "src/dashed-grid-fade-bottom-right.ts",
    "dashed-grid-fade-center": "src/dashed-grid-fade-center.ts",
    "gradient-glow-top": "src/gradient-glow-top.ts",
    "gradient-glow-bottom": "src/gradient-glow-bottom.ts",
    "spotlight-left": "src/spotlight-left.ts",
    "spotlight-right": "src/spotlight-right.ts",
    "circuit-board-basic": "src/circuit-board-basic.ts",
    "circuit-board-fade-top-left": "src/circuit-board-fade-top-left.ts",
    "circuit-board-fade-top-right": "src/circuit-board-fade-top-right.ts",
    "circuit-board-fade-top": "src/circuit-board-fade-top.ts",
    "circuit-board-fade-bottom": "src/circuit-board-fade-bottom.ts",
    "circuit-board-fade-bottom-left": "src/circuit-board-fade-bottom-left.ts",
    "circuit-board-fade-bottom-right": "src/circuit-board-fade-bottom-right.ts",
    "circuit-board-fade-center": "src/circuit-board-fade-center.ts",
    "grid-dots-basic": "src/grid-dots-basic.ts",
    "grid-dots-fade-center": "src/grid-dots-fade-center.ts",
    "blog-grid-author-cards": "src/blog-grid-author-cards.ts",
    "blog-cards-tagline-cta": "src/blog-cards-tagline-cta.ts",
    "blog-cards-read-time": "src/blog-cards-read-time.ts",
    "blog-category-overlay": "src/blog-category-overlay.ts",
    "blog-featured-popular": "src/blog-featured-popular.ts",
    "blog-related-articles": "src/blog-related-articles.ts",
    "blog-tech-insights": "src/blog-tech-insights.ts",
    "blog-horizontal-cards": "src/blog-horizontal-cards.ts",
    "blog-filtered-results": "src/blog-filtered-results.ts",
    "blog-masonry-featured": "src/blog-masonry-featured.ts",
    "blog-horizontal-timeline": "src/blog-horizontal-timeline.ts",
    "blog-grid-nine-posts": "src/blog-grid-nine-posts.ts",
    "article-hero-prose": "src/article-hero-prose.ts",
    "article-sidebar-sticky": "src/article-sidebar-sticky.ts",
    "article-toc-sidebar": "src/article-toc-sidebar.ts",
    "article-breadcrumb-social": "src/article-breadcrumb-social.ts",
    "article-compact-toc": "src/article-compact-toc.ts",
    "article-chapters-author": "src/article-chapters-author.ts",
    "article-split-animated": "src/article-split-animated.ts",
    "faq-simple-accordion": "src/faq-simple-accordion.ts",
    "faq-static-list": "src/faq-static-list.ts",
    "faq-centered-accordion": "src/faq-centered-accordion.ts",
    "faq-badge-support": "src/faq-badge-support.ts",
    "faq-numbered-list": "src/faq-numbered-list.ts",
    "faq-numbered-grid": "src/faq-numbered-grid.ts",
    "faq-split-help": "src/faq-split-help.ts",
    "faq-categorized-sections": "src/faq-categorized-sections.ts",
    "faq-muted-cards": "src/faq-muted-cards.ts",
    "faq-bordered-badge": "src/faq-bordered-badge.ts",
    "faq-gradient-categories": "src/faq-gradient-categories.ts",
    "faq-sidebar-navigation": "src/faq-sidebar-navigation.ts",
    "faq-card-categories": "src/faq-card-categories.ts",
    "faq-icon-benefits": "src/faq-icon-benefits.ts",
    "faq-rounded-cards": "src/faq-rounded-cards.ts",
    "faq-profile-sidebar": "src/faq-profile-sidebar.ts",
    "hero-badge-image-split": "src/hero-badge-image-split.ts",
    "hero-image-left-content": "src/hero-image-left-content.ts",
    "hero-centered-image-grid": "src/hero-centered-image-grid.ts",
    "hero-centered-screenshot": "src/hero-centered-screenshot.ts",
    "hero-pattern-badge-logos": "src/hero-pattern-badge-logos.ts",
    "hero-logo-centered-screenshot": "src/hero-logo-centered-screenshot.ts",
    "hero-pattern-logo-tech-stack": "src/hero-pattern-logo-tech-stack.ts",
    "hero-announcement-badge": "src/hero-announcement-badge.ts",
    "hero-tech-carousel": "src/hero-tech-carousel.ts",
    "hero-simple-centered-image": "src/hero-simple-centered-image.ts",
    "hero-platform-features-grid": "src/hero-platform-features-grid.ts",
    "hero-spiral-pattern-cards": "src/hero-spiral-pattern-cards.ts",
    "hero-split-spiral-shapes": "src/hero-split-spiral-shapes.ts",
    "hero-split-geometric-shapes": "src/hero-split-geometric-shapes.ts",
    "hero-community-survey-cta": "src/hero-community-survey-cta.ts",
    "hero-marketplace-scattered-images": "src/hero-marketplace-scattered-images.ts",
    "hero-badge-shadow-overlay": "src/hero-badge-shadow-overlay.ts",
    "hero-video-background-dark": "src/hero-video-background-dark.ts",
    "hero-grid-pattern-efficiency": "src/hero-grid-pattern-efficiency.ts",
    "hero-dashed-border-features": "src/hero-dashed-border-features.ts",
    "hero-design-carousel-portfolio": "src/hero-design-carousel-portfolio.ts",
    "hero-gradient-client-focused": "src/hero-gradient-client-focused.ts",
    "hero-premium-split-avatars": "src/hero-premium-split-avatars.ts",
    "hero-ui-library-showcase": "src/hero-ui-library-showcase.ts",
    "hero-fullscreen-background-image": "src/hero-fullscreen-background-image.ts",
    "hero-fullscreen-logo-cta": "src/hero-fullscreen-logo-cta.ts",
    "hero-gradient-avatars-rating": "src/hero-gradient-avatars-rating.ts",
    "hero-task-timer-animated": "src/hero-task-timer-animated.ts",
    "hero-ai-powered-carousel": "src/hero-ai-powered-carousel.ts",
    "hero-ad-campaign-expert": "src/hero-ad-campaign-expert.ts",
    "hero-adaptable-product-grid": "src/hero-adaptable-product-grid.ts",
    "hero-presentation-platform-video": "src/hero-presentation-platform-video.ts",
    "hero-grid-pattern-solutions": "src/hero-grid-pattern-solutions.ts",
    "hero-crm-streamlined": "src/hero-crm-streamlined.ts",
    "hero-billing-platform-logos": "src/hero-billing-platform-logos.ts",
    "hero-software-growth-video-dialog": "src/hero-software-growth-video-dialog.ts",
    "hero-conversion-video-play": "src/hero-conversion-video-play.ts",
    "hero-design-showcase-logos": "src/hero-design-showcase-logos.ts",
    "hero-video-overlay-stars": "src/hero-video-overlay-stars.ts",
    "hero-productivity-launcher-video": "src/hero-productivity-launcher-video.ts",
    "hero-hiring-animated-text": "src/hero-hiring-animated-text.ts",
    "hero-split-image-newsletter": "src/hero-split-image-newsletter.ts",
    "hero-centered-gradient-cta": "src/hero-centered-gradient-cta.ts",
    "hero-stats-social-proof": "src/hero-stats-social-proof.ts",
    "hero-feature-cards-grid": "src/hero-feature-cards-grid.ts",
    "hero-testimonial-image-grid": "src/hero-testimonial-image-grid.ts",
    "hero-design-system-3d": "src/hero-design-system-3d.ts",
    "hero-architecture-fullscreen": "src/hero-architecture-fullscreen.ts",
    "hero-innovation-image-grid": "src/hero-innovation-image-grid.ts",
    "hero-video-dialog-gradient": "src/hero-video-dialog-gradient.ts",
    "hero-minimal-centered-dark": "src/hero-minimal-centered-dark.ts",
    "hero-product-showcase-floating": "src/hero-product-showcase-floating.ts",
    "hero-saas-dashboard-preview": "src/hero-saas-dashboard-preview.ts",
    "hero-therapy-testimonial-grid": "src/hero-therapy-testimonial-grid.ts",
    "hero-mental-health-team": "src/hero-mental-health-team.ts",
    "hero-mentorship-video-split": "src/hero-mentorship-video-split.ts",
    "hero-business-operations-mosaic": "src/hero-business-operations-mosaic.ts",
    "hero-agency-animated-images": "src/hero-agency-animated-images.ts",
    "hero-welcome-asymmetric-images": "src/hero-welcome-asymmetric-images.ts",
    "hero-startup-launch-cta": "src/hero-startup-launch-cta.ts",
    "hero-enterprise-security": "src/hero-enterprise-security.ts",
    "hero-creative-studio-stacked": "src/hero-creative-studio-stacked.ts",
    "hero-digital-agency-fullscreen": "src/hero-digital-agency-fullscreen.ts",
    "hero-customer-support-layered": "src/hero-customer-support-layered.ts",
    "hero-shared-inbox-layered": "src/hero-shared-inbox-layered.ts",
    "hero-conversation-intelligence": "src/hero-conversation-intelligence.ts",
    "hero-business-carousel-dots": "src/hero-business-carousel-dots.ts",
    "hero-developer-tools-code": "src/hero-developer-tools-code.ts",
    "hero-ecommerce-product-showcase": "src/hero-ecommerce-product-showcase.ts",
    "hero-mobile-app-download": "src/hero-mobile-app-download.ts",
    "hero-pricing-comparison": "src/hero-pricing-comparison.ts",
    "hero-newsletter-minimal": "src/hero-newsletter-minimal.ts",
    "hero-coming-soon-countdown": "src/hero-coming-soon-countdown.ts",
    "hero-event-registration": "src/hero-event-registration.ts",
    "hero-portfolio-creative": "src/hero-portfolio-creative.ts",
        "case-studies-image-grid": "src/case-studies-image-grid.ts",
        "case-studies-testimonial-stats": "src/case-studies-testimonial-stats.ts",
        "case-studies-featured-border": "src/case-studies-featured-border.ts",
        "case-studies-stats-card": "src/case-studies-stats-card.ts",
        "case-study-prose-sidebar": "src/case-study-prose-sidebar.ts",
        "case-study-toc-social-sidebar": "src/case-study-toc-social-sidebar.ts",
        "case-study-stats-metrics": "src/case-study-stats-metrics.ts",
        "comparison-table-two-column": "src/comparison-table-two-column.ts",
        "comparison-feature-cards": "src/comparison-feature-cards.ts",
        "comparison-grid-badges": "src/comparison-grid-badges.ts",
        "comparison-metrics-rows": "src/comparison-metrics-rows.ts",
        "comparison-image-cards": "src/comparison-image-cards.ts",
        "comparison-table-tabs": "src/comparison-table-tabs.ts",
        "comparison-table-tooltips": "src/comparison-table-tooltips.ts",
        "comparison-feature-grid": "src/comparison-feature-grid.ts",
        "comparison-ai-models": "src/comparison-ai-models.ts",
        "comparison-legacy-modern": "src/comparison-legacy-modern.ts",
        "navbar-dropdown-menu": "src/navbar-dropdown-menu.ts",
        "navbar-centered-menu": "src/navbar-centered-menu.ts",
        "navbar-mega-menu": "src/navbar-mega-menu.ts",
        "navbar-enterprise-mega": "src/navbar-enterprise-mega.ts",
        "navbar-feature-grid": "src/navbar-feature-grid.ts",
        "navbar-floating-pill": "src/navbar-floating-pill.ts",
        "navbar-platform-resources": "src/navbar-platform-resources.ts",
        "navbar-image-preview": "src/navbar-image-preview.ts",
        "navbar-dark-icons": "src/navbar-dark-icons.ts",
        "navbar-animated-preview": "src/navbar-animated-preview.ts",
        "navbar-multi-column-groups": "src/navbar-multi-column-groups.ts",
        "navbar-sidebar-mobile": "src/navbar-sidebar-mobile.ts",
        "navbar-transparent-overlay": "src/navbar-transparent-overlay.ts",
        "navbar-education-platform": "src/navbar-education-platform.ts",
        "navbar-sticky-compact": "src/navbar-sticky-compact.ts",
        "navbar-search-focused": "src/navbar-search-focused.ts",
        "navbar-simple-links": "src/navbar-simple-links.ts",
        "navbar-split-cta": "src/navbar-split-cta.ts",
        "navbar-icon-links": "src/navbar-icon-links.ts",
        "navbar-tabbed-sections": "src/navbar-tabbed-sections.ts",
        "navbar-fullscreen-menu": "src/navbar-fullscreen-menu.ts",
        "logos-inline-tagline": "src/logos-inline-tagline.ts",
        "logos-certifications-grid": "src/logos-certifications-grid.ts",
        "logos-carousel-heading": "src/logos-carousel-heading.ts",
        "logos-partner-network": "src/logos-partner-network.ts",
        "logos-two-row-grid": "src/logos-two-row-grid.ts",
        "logos-marquee-muted": "src/logos-marquee-muted.ts",
        "logos-centered-simple": "src/logos-centered-simple.ts",
        "logos-numbered-carousel": "src/logos-numbered-carousel.ts",
        "logos-double-carousel-pattern": "src/logos-double-carousel-pattern.ts",
        "logos-minimal-carousel": "src/logos-minimal-carousel.ts",
        "logos-partner-grid-sidebar": "src/logos-partner-grid-sidebar.ts",
        registry: "src/registry.ts",
  utils: "lib/utils.ts",
  types: "src/types/index.ts",
};

export default defineConfig({
  ...sharedConfig,
  entry: allEntries,
  clean: true,
  // Add "use client" directive to client components after build
  onSuccess: async () => {
    const distDir = "dist";

    for (const entryName of clientEntryNames) {
      // Process both ESM and CJS outputs
      const files = [
        join(distDir, `${entryName}.js`),
        join(distDir, `${entryName}.cjs`),
      ];

      for (const filePath of files) {
        try {
          const content = readFileSync(filePath, "utf-8");
          // Only add if not already present
          if (!content.startsWith('"use client"')) {
            writeFileSync(filePath, `"use client";\n${content}`);
          }
        } catch {
          // File might not exist, skip
        }
      }
    }

    console.log("✓ Added 'use client' directive to client components");
  },
});
